### ISSUE TITLE
Options to select multiple rows in the table

### ISSUE THREAD

**Issue by saurabh1234** [ng-matero/extensions#1]
You have a build a example of basic table where there is an option to select multiple rows. Could you please tell me if there is any sort of callback which is getting fired when you mark the check box ?

Many thanks

**Comment by nzbin** [comment]
@saurabh1234 Thanks for your support. I'm very sorry I haven't written a document yet. The callback is `changeSort` and `changeSelect`

```html
<mtx-grid class="mat-elevation-z1"
          [data]="list"
          [columns]="columns"
          [loading]="isLoading"
          [frontPage]="true"
          [pageSizeOptions]="[5,10,50,100]"
          (changeSort)="changeSort($event)"
          (changeSelect)="changeSelect($event)">
</mtx-grid>
```
