### ISSUE TITLE
Bug: Datetime Picker

### ISSUE THREAD

**Issue by palmtreefrb** [ng-matero/extensions#100]
In a form group the set datetime value will only display date on initial render. If I set focus to the datetime picker then leave the control, the time will display.
![Peek 2022-03-29 16-56](https://user-images.githubusercontent.com/7799495/160725266-f4f3eafe-06ac-4306-8280-169311bdba6a.gif)

**Comment by viliks** [comment]
In template, move input after mtx-datetimepicker and datetimepicker type will be correctly initialized before input.

**Comment by nzbin** [comment]
I'm not sure what causes this problem. Can you provide a online demo?
