### ISSUE TITLE
Mtx-Grid rowSelected does only check the checkbox at the top

### ISSUE THREAD

**Issue by ChrTall** [ng-matero/extensions#104]
Can you explain how to use the rowSelected input of the Mtx-Grid ?
I provide a subset of my data array as rowSelected and would like that the rows of items in the rowSelected Array have a checked Checkbox.

```html
 <mtx-grid [data]="data"
           [columns]="displayedColumns"
           [rowHover]="true"
           [noResultText]="noResultText"
           [multiSelectable]="true"
           [multiSelectionWithClick]="true"
           [rowSelectable]="true"
           [cellSelectable]="false"
           [rowSelected]="selectedRows"
           [sortOnFront]="true"
           sortActive="name"
           sortDirection="asc"
           [sortDisableClear]="true"
           [sortDisabled]="false"
           sortStart="asc"
</mtx-grid>
```

**Comment by nzbin** [comment]
I'm not quite understand your question. Maybe you can checkout the [row selectable demo](https://ng-matero.github.io/extensions/components/grid/overview#row-selectable).

**Comment by ChrTall** [comment]
In your example you have an array of objects which are used from the data and use a slice of this array for [rowSelected].
Thats why nitrogen is selected.
I am calling an Api in ngOnInit and assign the result to data and a subset of this result to selectedRows, but no rows are selected.
If I log data and selectedRows I can see that I have a subset of the items from data in selectedRows and they both have the same properties.
Maybe the reason why it does not work me is because I use data from an Api ?

**Comment by ChrTall** [comment]
I figured out what caused the problem. I had assigned data from an outer component as rowSelected and assigned the data from the api to data. I think you are checking for reference equality which in my case was not equal, but the values were the same.
