### ISSUE TITLE
Feature request: integer format

### ISSUE THREAD

**Issue by WouterVandenputte** [ng-matero/extensions#105]
The color picker currently supports rgb, hex, hsl, hsv as formats, all written down as strings.
It would be nice to support integer formats as well. E.g. [how Dart encodes color](https://api.flutter.dev/flutter/dart-ui/Color-class.html): as a 4 byte digit where each byte is a value of the argb encoding.

**Comment by nzbin** [comment]
Thanks for your advice, I don't plan to support this feature and you should encode color by yourself.
