### ISSUE TITLE
[help wanted] Defining a theme

### ISSUE THREAD

**Issue by lamamyf** [ng-matero/extensions#107]
I'm getting a _SassError: Undefined variable._ while trying to define the theme included in the docs:

```
@use '@ng-matero/extensions' as mtx;

@include mtx.all-component-themes($theme);
@include mtx.all-experimental-component-themes($theme);
```
The _$theme_  variable isn't recognized, please help.

**Comment by nzbin** [comment]
https://github.com/ng-matero/extensions/blob/68e0ece073efa110ea4aa65b3cd70e28245fff11/projects/dev-app/src/styles.scss#L17-L31

https://material.angular.io/guide/theming

**Comment by lamamyf** [comment]
Thank you!!
