### ISSUE TITLE
Data Grid Custom Toolbar

### ISSUE THREAD

**Issue by RedonAlla** [ng-matero/extensions#11]
Great work.
I have a question, is it possible to add custom items on Data Grid Toolbar?
I want to add a 'Add Button' and a 'Search Textbox'

Or better put 'Columns Shown' button outside 'mtx-grid' component?

**Comment by RedonAlla** [comment]
Another question. 
I want to store tables columns visibility and order in database. Is there a callback to store the configs in database and load configs from database?

And the last thing, in Data Grid is missing error state, or I can't find how to implement it?

**Comment by nzbin** [comment]
> Great work.
> I have a question, is it possible to add custom items on Data Grid Toolbar?
> I want to add a 'Add Button' and a 'Search Textbox'
> 
> Or better put 'Columns Shown' button outside 'mtx-grid' component?

The toolbar template has been added.

**Comment by nzbin** [comment]
> Another question.
> I want to store tables columns visibility and order in database. Is there a callback to store the configs in database and load configs from database?
> 
> And the last thing, in Data Grid is missing error state, or I can't find how to implement it?

The grid columns have no two binding now. You can set `hide` property value of column definition manually.

**Comment by RedonAlla** [comment]
> > Great work.
> > I have a question, is it possible to add custom items on Data Grid Toolbar?
> > I want to add a 'Add Button' and a 'Search Textbox'
> > Or better put 'Columns Shown' button outside 'mtx-grid' component?
> 
> The toolbar template has been added.

THNX. Any example how to use it?

**Comment by RedonAlla** [comment]
> > Another question.
> > I want to store tables columns visibility and order in database. Is there a callback to store the configs in database and load configs from database?
> > And the last thing, in Data Grid is missing error state, or I can't find how to implement it?
> 
> The grid columns have no two binding now. You can set `hide` property value of column definition manually.

what I wanted is an event when column order/visibility change, to detect column order and witch column is checked as visible/invisible

**Comment by nzbin** [comment]
> > > Great work.
> > > I have a question, is it possible to add custom items on Data Grid Toolbar?
> > > I want to add a 'Add Button' and a 'Search Textbox'
> > > Or better put 'Columns Shown' button outside 'mtx-grid' component?
> > 
> > 
> > The toolbar template has been added.
> 
> THNX. Any example how to use it?

https://github.com/ng-matero/extensions/blob/65979c57e62c6a0412618d2a4a86ddfa105c2921/projects/demos/src/app/data-grid/data-grid-demo.component.html#L157-L165

**Comment by nzbin** [comment]
> > > Another question.
> > > I want to store tables columns visibility and order in database. Is there a callback to store the configs in database and load configs from database?
> > > And the last thing, in Data Grid is missing error state, or I can't find how to implement it?
> > 
> > 
> > The grid columns have no two binding now. You can set `hide` property value of column definition manually.
> 
> what I wanted is an event when column order/visibility change, to detect column order and witch column is checked as visible/invisible

`(columnHidingChange)` and `(columnMovingChange)`
You can review the [docs](https://nzbin.gitbook.io/material-extensions/data-grid). I will update the examples today.
