### ISSUE TITLE
Datetimepicker mtx-datetimepicker-content .mtx-calendar height have issue

### ISSUE THREAD

**Issue by SudhagarMurugesan** [ng-matero/extensions#110]
Hi @nzbin i just found a UI bug in the date time picker in the ng-matero extensions datetime picker,
while using the datetimepicker in the portrait mode and twelvehour format

![image](https://user-images.githubusercontent.com/87130720/176385931-0c59879f-382c-4aad-b909-d62bbaf534d8.png)
the calender content is overflowing above the body.

![image](https://user-images.githubusercontent.com/87130720/176386213-a6d737e2-317c-4e22-b261-5cbd2f0411f3.png)
for this 24hour format there is no issue

this calender content overflowing issue occurs while using the twelvehour mode.

P.S:
Really impressed on your work bro ! 
your contribution towards the community means a lot.

**Comment by nzbin** [comment]
Many thanks

**Comment by nzbin** [comment]
The new version 13.2.1 has fixed it.
