### ISSUE TITLE
[Popover] Add input to overlap the trigger

### ISSUE THREAD

**Issue by adrianbenjuya** [ng-matero/extensions#111]
First of all thanks for this nice set of extensions, are really useful.

I came to this repo because I've been using [this one](https://github.com/joejordanbrown/popover) and it didn't fully suite my needs. But it has this cool feature that makes the popover overlap the trigger, so it displays on top of the trigger.

I see the following in the docs for this component that makes me think that it was implemented once

![image](https://user-images.githubusercontent.com/17908930/177383765-03e95591-e695-4469-af6d-155a9f234b91.png)

Is there any chance to include this at some point in the future?

So far I managed to replicate this behavior by using the offsets inputs, but it would be really helpful to make it work automatically

**Comment by nzbin** [comment]
I'm sorry, this is my fault. I'll update the docs.

The popover is different from mat-menu and I removed the overlap trigger option when I added twelve positions. It's not very good to use overlap trigger for popover. Maybe you can use the mat-menu to implements some special demands if you need overlap trigger.

Thanks for your advice. I'll think about this issue again and have a try.

**Comment by adrianbenjuya** [comment]
Thanks for considering the feature, I might create a pull request if I have the time
