### ISSUE TITLE
Select background is transparent

### ISSUE THREAD

**Issue by AlonsoK28** [ng-matero/extensions#112]
Thanks for your library

I am using the [Select](https://ng-matero.github.io/extensions/components/select/overview) and the `background` of the `dropdown` is transparent, also the `icon` in the `input` is not visible

My enviroment:
`"@ng-matero/extensions": "^14.0.0"`
`"@angular/core": "^14.0.3"`

example 1.
![image](https://user-images.githubusercontent.com/37458700/177659998-ef76d6e5-1b27-45d3-8581-3e8a687ec1ff.png)

example 2.
![image](https://user-images.githubusercontent.com/37458700/177660028-a377f390-efd4-42de-99cd-62e0cf2338c6.png)

Greetings

**Comment by nzbin** [comment]
You should import the styles.
https://github.com/ng-matero/extensions#theming

**Comment by AlonsoK28** [comment]
😏
