### ISSUE TITLE
Customize date display in input field

### ISSUE THREAD

**Issue by JoranLive** [ng-matero/extensions#113]
Hello,

First of all, thank you a lot for your work!

How can we customize the displayed date in input field ?

```html
<mat-form-field>
  <input [mtxDatetimepicker]="startTimePicker" formControlName="startTime" matInput required readonly>
  <mtx-datetimepicker-toggle [for]="startTimePicker" matSuffix></mtx-datetimepicker-toggle>
  <mtx-datetimepicker #startTimePicker type="datetime" twelvehour="false"></mtx-datetimepicker>
</mat-form-field>
```
Even if it is set to 24 hour, the input field show 12 hours.

**Comment by nzbin** [comment]
https://github.com/ng-matero/extensions/blob/fdbf4dcc00236458ce9d012f71f45389cfa6ea6b/projects/dev-app/src/app/datetimepicker/datetimepicker-demo.module.ts#L20-L50

**Comment by JoranLive** [comment]
Thank you quite clear 👍

**Comment by nandhu042000** [comment]
Is there an option to display in 12 hr format with AM and PM instead of 24 hrs format??
