### ISSUE TITLE
[Slider] option to have fixed thumb labels

### ISSUE THREAD

**Issue by nunoarruda** [ng-matero/extensions#122]
Currently, the slider thumb labels are only shown when the slider is in focus:

https://user-images.githubusercontent.com/1189149/184652026-2f4c03dc-4cd1-4c3f-9ce7-001f98316283.mov

Can you folks add an option to make the thumb labels fixed?
This will help projects that want the thumb labels to be visible all the time/by default.

Thanks in advance.

**Comment by nzbin** [comment]
Thanks for your advice, I don't plan to support this feature because it's not a Material Spec.
