### ISSUE TITLE
[Slider] option to have a centralized slider

### ISSUE THREAD

**Issue by nunoarruda** [ng-matero/extensions#123]
Can you folks add an option to make a slider centralized? Something like this:

https://user-images.githubusercontent.com/1189149/184653845-4764b249-f52a-4613-bf1f-58039783bf5e.mov

This will help projects that need centralized sliders for things like calibration, for example.

Thanks in advance.

**Comment by nzbin** [comment]
Thanks for your advice, I don't plan to support this feature because it's not a Material Spec.
