### ISSUE TITLE
Missing errorStateMatcher directive

### ISSUE THREAD

**Issue by andreanaFelicione** [ng-matero/extensions#124]
Is possible to add a errorStateMatcher directive in mtx-select?

**Comment by nzbin** [comment]
v14.4.0 has added the `errorStateMatcher` directive. You can have a try.

**Comment by andrybany** [comment]
> v14.4.0 has added the `errorStateMatcher` directive. You can have a try.

Thanks, but I have to wait the [#119](https://github.com/ng-matero/extensions/issues/119#issue-1328834584) issue to be resolved before I can try the major version 14.
