### ISSUE TITLE
mtx-select problem

### ISSUE THREAD

**Issue by mrsly1996** [ng-matero/extensions#127]
![image](https://user-images.githubusercontent.com/57061755/187057893-c92c2ef2-11c3-428f-a08a-309bb5702b17.png)

there is a problem with mtx-select when we open dropdown on dialog. dropdown goes under dialog box. 
but in mat-select its diffrent.
dropdown must be top of all elements. thanks

**Comment by nzbin** [comment]
You can use the `appendTo` prop. Check the [ng-select API](https://github.com/ng-select/ng-select#api).

```html
<mtx-select appendTo="body"></mtx-select>
```
