### ISSUE TITLE
Bug: Expandable rows error for asynchronic data

### ISSUE THREAD

**Issue by magoarcano** [ng-matero/extensions#13]
I'm using remote data. If I enable expandable rows I get this error in console:

> core.js:6210 ERROR TypeError: Cannot read property 'forEach' of undefined
>     at MtxGridComponent.ngOnChanges (mtxGrid.js:1076)
>     at MtxGridComponent.wrapOnChangesHook_inPreviousChangesStorage (core.js:27085)
>     at callHook (core.js:4712)
>     at callHooks (core.js:4672)
>     at executeInitAndCheckHooks (core.js:4612)
>     at refreshView (core.js:11924)
>     at refreshDynamicEmbeddedViews (core.js:13283)
>     at refreshView (core.js:11929)
>     at refreshComponent (core.js:13358)
>     at refreshChildComponents (core.js:11635)
> 

The error is because this.data is null in the next lines of grid.component.ts:
```
// We should copy each item of data for expansion data
    if (this.expandable) {
      this.expansionRowStates = []; // reset

      this.data.forEach(_ => {
        this.expansionRowStates.push({ expanded: false });
      });
    }
```
I think it happens because it executes that code before the data is ready. Is it ok to just add `if this.data` before `this.data.forEach`?

**Comment by nzbin** [comment]
You should set the initial data to empty array `data=[]`. I will improve this issue.

**Comment by magoarcano** [comment]
ok. thanks!
