### ISSUE TITLE
[Grid] Rows expand on sorting

### ISSUE THREAD

**Issue by GT1902** [ng-matero/extensions#131]
Hello, 
I have a problem with mtx-grid in combination with expandable rows and sorting. When I click on sorting the data is sorted but some of the rows are expanded aftwards.  This seems to be a problem from angular material as you can see here: [Angular Issue](https://github.com/angular/components/issues/11990#issuecomment-421075196)

I cloned the repo and changed the animation in grid.component.ts as suggested and everything works fine:
```ts
    trigger('expansion', [
      state('collapsed, void', style({ height: '0', minHeight: '0', visibility: 'hidden' })),
      state('expanded', style({ height: '*', visibility: 'visible' })),
      transition('expanded <=> collapsed', animate('225ms cubic-bezier(0.4, 0.0, 0.2, 1)')),
      transition('expanded <=> void', animate('225ms cubic-bezier(0.4, 0.0, 0.2, 1)'))
    ]),
```

Could you please check if you can include this in a future release?

Thanks in advance and keep up the good work.

**Comment by nzbin** [comment]
Many thanks, maybe you can give me a PR.

**Comment by nzbin** [comment]
`v14.2.1` has fixed.
