### ISSUE TITLE
Mtx datetime picker | time part is not displayed if date with time was set.

### ISSUE THREAD

**Issue by IKitcera** [ng-matero/extensions#132]
Hello!

I found the issue while was trying to work with your library.
It will be very nice if you fix it.

I was working with reactive forms and values are usually sat in onInit or constructor. Unfortunately, mtx datetime picker requires to use AfterViewInit hook to set values. My problem is that time part is not displayed if date with time is set in ctor or ngOnInit

The issue is that this method is not called in necessary place on form values change.

https://github.com/ng-matero/extensions/blob/c8a133ff41f3257678322c8c2ceeaedbd298b84e/projects/extensions/datetimepicker/datetimepicker-input.ts#L406

**Comment by nzbin** [comment]
Can you give me an online example?

**Comment by nzbin** [comment]
Thanks, I have checked your demo and small fix it.
It will be ok if you put the `input` behind the `mtx-datetimepicker`.
https://stackblitz.com/edit/angular-ivy-fs9bma?file=src%2Fapp%2Fapp.component.html

**Comment by nzbin** [comment]
Duplicated with #100

**Comment by IKitcera** [comment]
Can you change this order in your demo / documentation to let the future developers not repeat my mistake?

**Comment by IKitcera** [comment]
Also thank you for quick answer

**Comment by nzbin** [comment]
The docs has updated and maybe I will improve this issue in the next version.
