### ISSUE TITLE
DateAdapter for luxon datetime format

### ISSUE THREAD

**Issue by JelleBruisten** [ng-matero/extensions#137]
This library is currently missing datetime format support for luxon datetime formats, could we add this? 

I would be willing to submit a pull request regarding this, I already have a working example.

**Comment by nzbin** [comment]
```
npm i @ng-matero/extensions-luxon-adapter
```

**Comment by nzbin** [comment]
@JelleBruisten Would you be interested in adding the date-fns adapter (#93)?

**Comment by nzbin** [comment]
Great! Thanks for your help.
