### ISSUE TITLE
data grid translate

### ISSUE THREAD

**Issue by gacekm** [ng-matero/extensions#14]
Hi,

How is the best pratice use ngx-translate for header columns and button title of show columns?

The header template works ok but in MtxGridColumn is field i18n. I define the translate in colums array
```ts
this.translate.get(['TEST.operation']).subscribe((res: any) => {
      var gridColumns: MtxGridColumn[] = [
        {field: 'create_at',header: res['TEST.operation']}, 
```
but are no change after change langue. I used 
```ts
this.translate.onLangChange.subscribe((params: LangChangeEvent) => {
        this.fillGridColumns();
```
but columns not refresh.
Could you help me please.

**Comment by nzbin** [comment]
You can try this
```ts
    this.translate.get(['TEST.operation']).subscribe((res: any) => {
      this.columns.forEach(item => {
        item.header = res[item.i18n];
      });
      this.columns = this.columns.filter(_ => true);
    });
```

**Comment by nzbin** [comment]
V9.10.0 has add i18n solution ([Demo](https://ng-matero.github.io/extensions/data-grid#i18n-ngx-translate))
