### ISSUE TITLE
Add AM/PM to time picking workflow

### ISSUE THREAD

**Issue by andyrue** [ng-matero/extensions#142]
When selecting a time using the twelve-hour format, you choose your hour and you choose the minute and it defaults to whatever AM/PM period you are currently in. After choosing the minutes, it would be great if it presented the option of AM or PM. Otherwise you have to open it back up, click on the time area and then you can change the period. It's not super clear that you need to click on the time before being able to change the AM/PM either.

**Comment by nzbin** [comment]
v14.6.0 has support manual time input. You can check the docs and let me know if it can solve your issues.

**Comment by andyrue** [comment]
Thank you for the update. The example on the docs site works well, however I can't seem to get the update to show in my local code. I've updated to 14.6.0 but it still looks the same there. I didn't notice any additional option that would need to be enabled for it. I removed node_modules and reinstalled all packages but still no change. Can you verify the update is in the latest npm package?
