### ISSUE TITLE
update to angular v15

### ISSUE THREAD

**Issue by damingerdai** [ng-matero/extensions#150]
1.  update [angular v15](https://github.com/angular/angular/releases/tag/15.0.0)
2. update [angular material v15](https://github.com/angular/components/releases/tag/15.0.0)
3. update [angular eslint v15](https://github.com/angular-eslint/angular-eslint/releases/tag/v15.0.0)
4. [Migrating to MDC-based Angular Material Components](https://material.angular.io/guide/mdc-migration)

**Comment by JelleBruisten** [comment]
I found a issue that when updating to angular 15 the datepicker will suddenly render like this:

![image](https://user-images.githubusercontent.com/4212850/205589845-0fef58f0-5a00-45ed-b069-e57ddca17c62.png)

I checked out why, and it seems that there was a release/change that changed the use of a `<span>` to a `<button mat-button>` . This will cause the datepicker to render the leftside incorrectly because angular material moved all mat-button to legacy and the datepicker is referencing the new version?.

**Comment by nzbin** [comment]
@JelleBruisten OK, I know this issue. Because the class `.mat-button` is replaced with `.mdc-button`. I will improve it.

**Comment by JelleBruisten** [comment]
Yeah, otherwise the datepicker seems to be working correctly with v15. Cannot speak for other components currently in `@ng-matero/extensions` since currently we don't use them, we might in future though!

**Comment by JelleBruisten** [comment]
@nzbin 

I does seem to work however the time seems a bit off in comparison with older version:

![image](https://user-images.githubusercontent.com/4212850/205949667-ea46b6b9-ddbc-46c7-aa99-91298e117f88.png)

For now I will use a small workaround:
```css
.mtx-calendar-header-date.mdc-button.mat-mdc-button {
  height: unset;
}
```
This will make it like this:
![image](https://user-images.githubusercontent.com/4212850/205949997-923ec813-6e78-4bc4-90aa-c98552eb1caf.png)

**Comment by mastersamm-db** [comment]
is this version 14.6.2 is not compatible with Angular 14, the css styles are not applied correctly you have to force them manually one case, I am going to try with version 14.4.1 that came out before the version of angular 15.

```
.mtx-calendar-header .mtx-calendar-header-year {
    line-height: 24px !important;
  }

  .mtx-calendar-header .mtx-calendar-header-year{
    padding: 0 4px !important;
  }

.mtx-calendar-header .mtx-calendar-header-date {
    padding: 0 4px !important;
    line-height: inherit !important;
}

.mtx-calendar-header .mtx-calendar-header-hours {
    padding: 0 4px !important;
    line-height: inherit !important;
}

.mtx-calendar-header .mtx-calendar-header-minutes {
    padding: 0 4px !important;
    line-height: inherit !important;
}

.mtx-calendar .mtx-calendar-header-ampm {
    padding: 4px !important;
}
.mtx-calendar-header .mtx-calendar-header-ampm{
    line-height: inherit !important;
}
```

**Comment by nzbin** [comment]
Now v15 has released.
