### ISSUE TITLE
Disable checkbox of row by condition

### ISSUE THREAD

**Issue by hanogin** [ng-matero/extensions#152]
How to make row selectable only if a condition mucth?
Either to disable the selection in the first place, or after the user click, i'll make some check and decided whether the checkbox is allowed, if condition not match id like the buton to remaiin unselect.

I try to work with the rowSelected property by setting the only rows that i want, it workd half away,
The row indeed reset to default style (like unselect) but the checkbox still remain check.

**Comment by nzbin** [comment]
Try the `rowSelectionFormatter` prop:

```html
<mtx-grid [rowSelectionFormatter]="rowSelectionFormatter"></mtx-grid>
```
```ts
rowSelectionFormatter: MtxGridRowSelectionFormatter = {
  disabled: data => data.name === 'Boron',
  hideCheckbox: data => data.name === 'John',
};
```

https://ng-matero.github.io/extensions/components/grid/overview#row-selectable

**Comment by hanogin** [comment]
Great! 
Thank you!
