### ISSUE TITLE
[Tooltip] How to pass data dynamically to [mtxTooltip] directive ?

### ISSUE THREAD

**Issue by AlonsoK28** [ng-matero/extensions#163]
Its possible to pass data dynamically inside of [mtxTooltip](https://ng-matero.github.io/extensions/components/tooltip/overview) directive to use it into `template`?

- example
```example.js
<div *ngFor="let result of searchResults">
  <button mat-raised-button 
    // how to pass custom data inside #tooltipTpl here ?
    [mtxTooltip]="tooltipTpl:result.image">
    Action
  </button>
</div>

<ng-template #tooltipTpl>
   // how to get here the data arguments ?
   <img src="result.image">
</ng-template>
```

**Comment by nzbin** [comment]
You can try the following way:

```html
<div *ngFor="let result of searchResults">
  <button mat-raised-button  [mtxTooltip]="tooltipTpl">Action</button>
  <ng-template #tooltipTpl>
     <img src="result.image">
  </ng-template>
</div>
```

**Comment by AlonsoK28** [comment]
amazing 

![image](https://user-images.githubusercontent.com/37458700/209046209-b6e65be5-3381-4e83-9ac4-8ca22fae7879.png)

**Comment by nzbin** [comment]
I think the popover is better than tooltip if you want to show the image.

**Comment by AlonsoK28** [comment]
> I think the popover is better than tooltip if you want to show the image.

Looks amazin 😎

![image](https://user-images.githubusercontent.com/37458700/209050521-ba8e24d8-c3b6-4f53-a546-6fbb8cce9bbc.png)

**Comment by AlonsoK28** [comment]
I get the following error when update to `@ng-matero/extensions@14.6.3`

```
ERROR NullInjectorError: R3InjectorError(DashboardModule)[InjectionToken mtx-popover-scroll-strategy -> InjectionToken mtx-popover-scroll-strategy -> InjectionToken mtx-popover-scroll-strategy -> InjectionToken mtx-popover-scroll-strategy]: 
  NullInjectorError: No provider for InjectionToken mtx-popover-scroll-strategy!
```

I import only `MtxPopoverModule` into my module, I need some more?

**Comment by nzbin** [comment]
Which angular version do you use?

**Comment by AlonsoK28** [comment]
> Which angular version do you use?

Lastest Angular 14

"@angular/animations": "^14.2.12",
    "@angular/cdk": "^14.2.3",
    "@angular/common": "^14.2.12",
    "@angular/compiler": "^14.2.12",
    "@angular/core": "^14.2.12",
    "@angular/fire": "^7.4.1",
    "@angular/flex-layout": "^14.0.0-beta.41",
    "@angular/forms": "^14.2.12",
    "@angular/material": "^14.2.3",
    "@angular/platform-browser": "^14.2.12",
    "@angular/platform-browser-dynamic": "^14.2.12",
    "@angular/router": "^14.2.12",
    "@angular/service-worker": "^14.2.12",

**Comment by nzbin** [comment]
I created an online example for v14 and I don't find any issues.
https://stackblitz.com/edit/angular-ivy-2kqseo?file=src%2Fapp%2Fapp.component.ts

**Comment by AlonsoK28** [comment]
its working very well
