### ISSUE TITLE
(question) how to implement a theme toggle dark theme/ligth theme

### ISSUE THREAD

**Issue by AlonsoK28** [ng-matero/extensions#165]
Hi dude 😏

Can you provide an example of how you implement the `theme toggle` like your docs page ?

ligth theme enabled
![image](https://user-images.githubusercontent.com/37458700/209759637-c4b045ad-d41c-47bf-9765-ec04d4bb49f2.png)

dark theme enabled
![image](https://user-images.githubusercontent.com/37458700/209759652-8e298032-188c-45e4-80cf-9cb2773b7451.png)

Very thanks for your support

Greetings 😎

**Comment by nzbin** [comment]
I created a dark theme class and toggle the class.

https://github.com/ng-matero/extensions/blob/befc39de185a84fa3ff25ca189f40c10621d2c3b/projects/docs/src/styles.scss#L28-L45

**Comment by AlonsoK28** [comment]
😏😏😏😏😏😏😏
