### ISSUE TITLE
photoviewer dependency is CommonJS

### ISSUE THREAD

**Issue by ChrTall** [ng-matero/extensions#166]
the photoviewer dependency causes Warnings when compiling an angular app with ng-matero extensions.

node_modules/@ng-matero/extensions/fesm2020/mtxGrid.mjs depends on 'photoviewer'. CommonJS or AMD dependencies can cause optimization bailouts.

Is there a reason why you added photoviewer as a dependency? I had a look at photoviewer but it I do not know where it is used in the project and if it could be replaced or dropped.

**Comment by nzbin** [comment]
Please check the [Remote Data](https://ng-matero.github.io/extensions/components/grid/overview#remote-data) example of data grid and click the avatar image. It can be enlarged if you use the image type in the column's definition.

```ts
columns: MtxGridColumn[] = [
  ...
  { header: 'Owner Avatar', field: 'owner.avatar_url', type: 'image' },
  ...
]
```
