### ISSUE TITLE
data-grid: Feature request: ability to hide default sort icon while keep the arrow icon

### ISSUE THREAD

**Issue by hanogin** [ng-matero/extensions#167]
First,  thanks for this awesome extensions.

Sometimes i have a lot of column and i want to decrese the width of the column to a minimum, and i found that the sort icon take some  space i could use.
I know i can use custom header but then i lost the arrow icon function wich i want to keep.

Maybe you can add an optinal paramater to show/hide the sort icon while keep the arrow icon?

Thnak you

**Comment by nzbin** [comment]
Please use CSS to hide the sort icon.
```css
.mtx-grid .mat-sort-header-icon {
  display: none;
}
```
