### ISSUE TITLE
data-grid: Feature request: add horizontal optional scroll on top

### ISSUE THREAD

**Issue by hanogin** [ng-matero/extensions#168]
Right now we have default orizontal scroll on the bottom of the table/div
Is there a way to add one on top - right under the headers as show in the picture
It can be very handy if we show alot of rows, so insted to go down only for scroll we can do it from above as well.

![Capture](https://user-images.githubusercontent.com/19567137/210554116-1c3199e1-fe11-408c-b93f-19c570efab7f.PNG)

**Comment by nzbin** [comment]
I don't know how to implement this feature. Can you give me some examples or libraries which have this feature?

**Comment by nzbin** [comment]
I will close this issue as you can't give me more informations. You can open it again if you still have questions.

**Comment by hanogin** [comment]
Sorry for not answering for a long time.

I do not know any library that implement such a feature.

I'm not a css guy at all, all i can do is search and this is what i found: https://stackoverflow.com/questions/3934271/horizontal-scrollbar-on-top-and-bottom-of-table

Maybe the right way is not to implement this futrue in this library, but to do some a warper to mtx div as show in the link.

What do yout think?

**Comment by nzbin** [comment]
Thanks for your advice, I won't implement it because this is not a common feature.
