### ISSUE TITLE
Mtx-Select: show required asterisk when using required validator

### ISSUE THREAD

**Issue by nicolasstevenyates** [ng-matero/extensions#179]
Since Angular 13 Material Components show automatically an asterisk symbol next to the mat-label if the form control is required.
Pre Angular 13 this was only displayed for template driven forms. Angular 13 added this functionality to reactive forms.

This is should also work on Mtx-select component when using a required Validator with Angular Reactive Forms.

These images show a matInput form Control and an mtx-select form control. As you can see the mtx-select form control is missing the * next to the label even it has the required validator.

![image](https://user-images.githubusercontent.com/44491178/216990024-390d9a26-9a8b-43f9-826e-bc513920e6f2.png)
![image](https://user-images.githubusercontent.com/44491178/216990112-783ea344-d7f3-4965-a58f-e83466f46868.png)

**Comment by nzbin** [comment]
`15.0.3` has fixed this issue, please have a try.
