### ISSUE TITLE
translation or custom text for mtx-dialog confirm()

### ISSUE THREAD

**Issue by magoarcano** [ng-matero/extensions#18]
`confirm()` of MtxDialog has hardcoded 'OK' and 'CLOSE' for the onClose() and onOK() buttons. 
The dialog is used in the custom buttons column of mtx-grid.
It would be nice if those texts can be translated with i18n or at least customized in the MtxGridColumnButton interface

**Comment by nzbin** [comment]
You can customize buttons in the following way.
https://github.com/ng-matero/extensions/blob/65979c57e62c6a0412618d2a4a86ddfa105c2921/projects/demos/src/app/dialog/dialog-demo.component.ts#L36-L64

**Comment by nzbin** [comment]
You can customize the buttons with `cellTemplate`

**Comment by Luperco** [comment]
Hi, sorry for _necroposting_, but with cellTemplate I can customise a button in a data grid cell. 
How can I use it for Confirm and Alert dialogs?

Thank you anyway for your work on the library. Very useful.
