### ISSUE TITLE
Some Modules are not found in angular material when import module from mtx.

### ISSUE THREAD

**Issue by HiteshWork13** [ng-matero/extensions#186]
![image](https://user-images.githubusercontent.com/97155081/223060367-7f359a9e-215a-47ff-a55b-e1f5e3997491.png)

I am using this dependencies in my package.json

![image](https://user-images.githubusercontent.com/97155081/223060759-f1538cb7-ebb9-4a49-badf-14c9d151f01c.png)

when I import `MtxDatetimepickerModule` into my module, angular throws an error which I show in first screenshot.

same kind of error I am facing when import `dataGridModule`

**Comment by nzbin** [comment]
You should align the major version with Angular
```
npm i @ng-matero/extensions@14
```
