### ISSUE TITLE
Sorting with Custom Header Template

### ISSUE THREAD

**Issue by technbuzz** [ng-matero/extensions#187]
I tried adding customer header template and sorting but they both don't work. The custom header templates takes over. Is there a way to make them work together?

**Comment by nzbin** [comment]
Use  `headerExtraTemplate` instead of `headerTemplate`

**Comment by technbuzz** [comment]
Yes that works, is it possible to not always show the extraTemplate only when we hover the column header?

**Comment by nzbin** [comment]
> Yes that works, is it possible to not always show the extraTemplate only when we hover the column header?

Maybe you can achieve with CSS.

**Comment by technbuzz** [comment]
Do you mean to add this feature, inherently inside the library or consumer of library can add it via a class or something?

**Comment by nzbin** [comment]
> Yes that works, is it possible to not always show the extraTemplate only when we hover the column header?

I created an online example, you can take a look.
https://stackblitz.com/edit/angular-material-15-wdnkbe?file=src%2Fapp%2Fapp.component.html
