### ISSUE TITLE
Material grouped multiselect checkbox

### ISSUE THREAD

**Issue by magicnov** [ng-matero/extensions#188]
Is there grouped multi select checkbox component wrapper from ng-select? Can`t find in the documentation.
The one from ng-select has default checkboxes, not material styled..
![image](https://user-images.githubusercontent.com/54899018/224010216-a77acb3c-71d9-47d0-8afb-1afc925b39f1.png)

**Comment by nzbin** [comment]
The ng-select use custom template to show checkbox, so you can also customize with mat-checkbox.
https://github.com/ng-select/ng-select/blob/master/src/demo/app/examples/multi-checkbox-group-example/multi-checkbox-group-example.component.html

```html
<mtx-select ...>
  <ng-template ng-optgroup-tmp ...>
    <mat-checkbox [checked]="item$.selected"/>
  </ng-template>
  <ng-template ng-option-tmp ...>
    <mat-checkbox [checked]="item$.selected"/>
  </ng-template>
</mtx-select>
```

**Comment by magicnov** [comment]
> The ng-select use custom template to show checkbox, so you can also customize with mat-checkbox. https://github.com/ng-select/ng-select/blob/master/src/demo/app/examples/multi-checkbox-group-example/multi-checkbox-group-example.component.html
> 
> ```
> <mtx-select ...>
>   <ng-template ng-optgroup-tmp ...>
>     <mat-checkbox [checked]="item$.selected"/>
>   </ng-template>
>   <ng-template ng-option-tmp ...>
>     <mat-checkbox [checked]="item$.selected"/>
>   </ng-template>
> </mtx-select>
> ```

Thank you! It worked.
Another question, is there a way to include only legacy components styles, like we can do in @angular/material?
![image](https://user-images.githubusercontent.com/54899018/224279411-213f196c-6e69-4c6a-a350-3c75ae57700e.png)

**Comment by nzbin** [comment]
I'm sorry, the v15 doesn't have legacy components.
