### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by technbuzz** [ng-matero/extensions#190]
This library has a lot of potential and can be improved further. I wanted to know how one can contribute to it. I didn't see any contribution guides or at least is not visible enough on the readme.

**Comment by nzbin** [comment]
I'm not sure what contribution guides you need. Just clone this repo and give PR. You can find all components in the [extensions folder](https://github.com/ng-matero/extensions/tree/master/projects/extensions).

**Comment by JelleBruisten** [comment]
Could be your first contribution a contribution guide 😄
