### ISSUE TITLE
Lazy Loading expansion template data grid

### ISSUE THREAD

**Issue by Ghez239** [ng-matero/extensions#196]
How can i lazy load the expansion template in mtx grid (v13)

**Comment by nzbin** [comment]
```html
<ng-template #expansionTpl let-row let-expanded="expanded">
  <div *ngIf="expanded"></div>
</ng-template>
```

**Comment by Ghez239** [comment]
ok thanks, but with like 50 elements in the grid, animation lags, is there a way to solve it?

**Comment by nzbin** [comment]
> ok thanks, but with like 50 elements in the grid, animation lags, is there a way to solve it?

I'm not sure, maybe too many data has some performance issue.
