### ISSUE TITLE
Translate mtx-select texts

### ISSUE THREAD

**Issue by lilletech** [ng-matero/extensions#197]
Hi,

I switch my lib ng-select to mtx-select. 
It works like a charm but these lines don't have any effects on the component.
I need to customize text to the french language. 

````
export class SharedModule {
  constructor(private ngSelectConfig: NgSelectConfig) {}

  configureNgSelect(): void {
    this.ngSelectConfig.notFoundText = `Aucun résultat`;
    this.ngSelectConfig.clearAllText = `Effacer tout`;
    this.ngSelectConfig.loadingText = `Chargement en cours`;
  }
}
``````
(the sharedmodule imports & exports the MtxSelectModule)

Any idea to make it working ?

**Comment by nzbin** [comment]
I'm sorry, this is a lost feature. I will add it in the next version.

**Comment by nzbin** [comment]
Now 15.3.0 has support global config, please have a try.

```
{
  provide: MTX_SELECT_DEFAULT_OPTIONS, 
  useValue: {...}
}
```
