### ISSUE TITLE
Date Time Picker Action buttons not shown

### ISSUE THREAD

**Issue by trmobile** [ng-matero/extensions#199]
Not able to enable or display Action Button 'Ok' and 'Cancel' in Date Time PIcker

**Comment by nzbin** [comment]
Which version do you use? Only v14 or above has action buttons.

**Comment by trmobile** [comment]
I'm using v12, that's the reason. 
How can we set the DateFormat dynamically? or from Input?

**Comment by nzbin** [comment]
> I'm using v12, that's the reason. How can we set the DateFormat dynamically? or from Input?

It doesn't support change date format dynamically. Please follow the issue #185.
