### ISSUE TITLE
[MtxDatetimepicker] Using type "year" doesn't work

### ISSUE THREAD

**Issue by Kristjan-Kiolein** [ng-matero/extensions#204]
How to replicate:
* Version: `"@ng-matero/extensions": "^14.2.0",`
* Add type year to datetimepicker: `<mtx-datetimepicker [type]="'year'"></mtx-datetimepicker>`
* Try to select year

There doesn't seem to be [date format switch option](https://github.com/ng-matero/extensions/blob/a7399c2ebbd8eccf7e4f220ec7b2e1a3f7cf4155/projects/extensions/datetimepicker/datetimepicker-input.ts#L310) for "year" even though there is [MtxDatetimepickerType  type for that](https://github.com/ng-matero/extensions/blob/master/projects/extensions/datetimepicker/datetimepicker-types.ts)

**Comment by nzbin** [comment]
Can you use the latest version of v14 and test again? If you still have question, please give me an online example.

**Comment by Kristjan-Kiolein** [comment]
Was missing MtxNativeDatetimeModule import 🤦

Not related to ticket but how to change display format to just `yyyy`:
https://stackblitz.com/edit/angular-material-13-starter-x1xj4z-qfqxbk?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts

**Comment by Kristjan-Kiolein** [comment]
Was missing MtxNativeDatetimeModule import 🤦

Not related to ticket but how to change display format to just `yyyy`:
https://stackblitz.com/edit/angular-material-13-starter-x1xj4z-qfqxbk?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts
