### ISSUE TITLE
Popover position issue

### ISSUE THREAD

**Issue by abdallahemad94** [ng-matero/extensions#206]
when setting the position for the popover to ['before', 'below'] for example it doesn't take effect on inspection of the html the popover has mtx-popover-after-below which isn't right instead it should be mtx-popover-before-below 
the issue exists on the demo [link](https://ng-matero.github.io/extensions/components/popover/overview)

**Comment by nzbin** [comment]
Because there has no enough space to place the left, so it will place right automatically. You can drag the button around and test again.
