### ISSUE TITLE
 grid 是否目前不支持数据懒加载？

### ISSUE THREAD

**Issue by Sanotsu** [ng-matero/extensions#21]
您好,因为我看extensions/data-grid/grid.component.ts中有直接绑定
```
 this.dataSource.paginator = this.paginator;
```
因为我对angular-material paginator的测试结果显示,绑定在一起之后paginator的length好像会被datasource的data.length覆盖。虽`@Input() length = 0`目前没有效果。
所以想问暂时mat-grid还是无法支持自输入length属性吗?

**Comment by nzbin** [comment]
默认前端分页，设置 `pageOnFront=false` 即可

**Comment by Sanotsu** [comment]
@nzbin 我試`[pageOnFront]="false"`應該只是隱藏了mtx-grid自帶的分頁組件，所以還是自己使用mat-paginator自己寫一個分頁的邏輯操作嗎？

**Comment by nzbin** [comment]
直接看这个例子吧 
https://github.com/ng-matero/ng-matero/blob/16f0e1044bccc6e9a9aa14cb43a08ccee3c6f505/src/app/routes/tables/remote-data/remote-data.component.html#L28-L37
