### ISSUE TITLE
standalone components support

### ISSUE THREAD

**Issue by damingerdai** [ng-matero/extensions#216]

**Comment by JelleBruisten** [comment]
What do you propose? Currently you can just fine import the module in any standalone component already. Do you mean splitting up `MtxDatetimepickerModule` into standalone parts?

**Comment by damingerdai** [comment]
migrate all components to standalone components  and re-export these components in module

**Comment by JelleBruisten** [comment]
Can you make a pull request for this?

**Comment by nzbin** [comment]
The Angular Material doesn't switch to standalone component yet. I will follow up after they migrated.

**Comment by damingerdai** [comment]
i  fully support your opinion, but I hope we can complete the unit testing.

**Comment by nzbin** [comment]
Now Angular Material has migrated to standalone component, I will also migrate for v17.

**Comment by nzbin** [comment]
17.1.0 has converted all components to standalone.
