### ISSUE TITLE
Feature: MtxGrid Sidescrolling with mouse-wheel

### ISSUE THREAD

**Issue by ChrTall** [ng-matero/extensions#218]
When you have a MtxGrid with lots of columns that are larger than the provided page space, the grid has a horizontal scroll bar.
Would it be possible to make it scrollable with the mouse-wheel?
Currently only vertical scroll bars can be scrolled with the mouse-wheel.
Some strategy would have to be added for Grids that have a horizontal and a vertical scroll bar though.

Example of a MtxGrid with a horizontal scroll bar.
https://ng-matero.github.io/extensions/components/grid/overview#column-pinnable

Example of a MtxGrid with a vertical scroll bar.
https://ng-matero.github.io/extensions/components/grid/overview#column-pinnable

**Comment by nzbin** [comment]
You can hold `Shift` key for horizontal scrolling.
