### ISSUE TITLE
[mtx-select] Please provide more info about how this may be used

### ISSUE THREAD

**Issue by cristiansandru11** [ng-matero/extensions#22]
<img width="397" alt="Screenshot 2020-06-22 at 19 01 13" src="https://user-images.githubusercontent.com/40002023/85309083-c0377c80-b4ba-11ea-9572-5eebaa66a849.png">

Any help would be much appreciated!

```
  <mat-form-field>
    <mtx-select
      [items]="cities"
      bindLabel="name"
      bindValue="id"
      [multiple]="true"
      placeholder="Select reviewers"
      clearAllText="Clear"
      [formControl]="formGroup.controls.reviewerIds"
    >
    </mtx-select>
  </mat-form-field>
```

**Comment by nzbin** [comment]
The `mtx-select` is just a wrapper for `ng-select`, you can read the `ng-select` docs.

**Comment by cristiansandru11** [comment]
Many thanks for answering, it worked. Could u please provide a stackblitz of your demo? It would be much easier for everyone to understand how to use your library, or update the repo documentation.

Have a nice evening & thx again!

**Comment by nzbin** [comment]
The docs has just finished refacted. I will improve it as soon as possible.
