### ISSUE TITLE
"mtx-grid rowSelectable=true", does not automatically fill the cell.

### ISSUE THREAD

**Issue by nuxwork** [ng-matero/extensions#221]
```
<mtx-grid
[rowSelectable]="true"
</mtx-grid>
```

<img width="1337" alt="Screen Shot 2023-05-30 at 11 33 01 AM" src="https://github.com/ng-matero/ng-matero/assets/4026598/3079f156-bac6-417a-9672-4289e327078e">

```
<mtx-grid
[rowSelectable]="false"
</mtx-grid>
```
<img width="1328" alt="Screen Shot 2023-05-30 at 9 52 09 AM" src="https://github.com/ng-matero/ng-matero/assets/4026598/9abbdfc9-862e-42e1-96a9-c0b1cb226a2f">

**Comment by nzbin** [comment]
Can you give me an online example?
