### ISSUE TITLE
Data Grid row expansion and collapse not possible programmatically.

### ISSUE THREAD

**Issue by ajit-chougule** [ng-matero/extensions#223]
Data Grid row expansion and collapse not possible programmatically.

![image](https://github.com/ng-matero/extensions/assets/96882485/084678c1-1b56-4c2b-9dd1-16300a6c0788)

We don't have control to toggle expand or collapse by using true or false flag.
Or if it is possible, please let me know..
Thank You......

**Comment by nzbin** [comment]
Please check this issue https://github.com/ng-matero/extensions/issues/191

**Comment by ajit-chougule** [comment]
I checked example given in issue #191, and it works for ng-matero v15 and above.
but it's not working below v14.
----------------------------------
In my case, I need expansionRowStates property. 
And it is availbale under "import { MtxGrid } from '@ng-matero/extensions/grid';".
but this is not available below v14.

Could you please check this ?
or any other way is available, Please let me know..

Thank You..

**Comment by nzbin** [comment]
I'm sorry, there has a break change in v15. You should import `MtxGridComponent` instead of `MtxGrid` in v14.
```ts
import { MtxGridComponent } from '@ng-matero/extensions/grid';
```
