### ISSUE TITLE
mtx-grid: keep rows checkbox selection in case of pagination data from remote

### ISSUE THREAD

**Issue by SYS64738** [ng-matero/extensions#226]
Hi, there's a way to preserve rows checkbox selection when data comes from remote (http) after page navigation ? I cannot find a way to check programmatically a row.

Thank you for your support.

**Comment by nzbin** [comment]
```html
<mtx-grid [rowSelectionFormatter]="rowSelectionFormatter"></mtx-grid>
```

https://github.com/ng-matero/extensions/blob/63ae586d759d2c6014421d444dc64de34a01007e/projects/dev-app/src/app/grid/grid-demo.component.ts#L29-L32
