### ISSUE TITLE
Localization and Automatic Message Support Like Mat-Error

### ISSUE THREAD

**Issue by kharazian** [ng-matero/extensions#228]
Hello,

I have a question regarding the localization support in your component. Is there an equivalent component like mat-error in your library that automatically handles localization and displays error messages, similar to the localization in header and pagination feature in mtx-grid component?

thanks

**Comment by nzbin** [comment]
I'm sorry, it only supports using `toolbarTemplate` or `paginationTemplate` to customize.
https://github.com/ng-matero/extensions/blob/63ae586d759d2c6014421d444dc64de34a01007e/projects/dev-app/src/app/grid/grid-demo.component.html#L122-L124

**Comment by kharazian** [comment]
Thank you for your response. I appreciate the clarification. I'll explore using the available options to customize the mat-error component according to my needs. Your assistance is greatly appreciated!
