### ISSUE TITLE
怎么更新版本啊？

### ISSUE THREAD

**Issue by zouchengtao** [ng-matero/extensions#23]
我用extensions里面的表格会抛错，感觉是版本没更新的问题

![image](https://user-images.githubusercontent.com/20035635/85988619-e365ad00-ba21-11ea-9f88-4f3837c67916.png)

**Comment by nzbin** [comment]
现在用的是什么版本，另外贴一下代码看看

**Comment by zouchengtao** [comment]
> 现在用的是什么版本，另外贴一下代码看看

版本好像是0.4.4
![image](https://user-images.githubusercontent.com/20035635/86074358-5faacf80-bab8-11ea-8490-36a476984568.png)
然后代码就是按demo：
`<mtx-grid [data]="list"
          [columns]="columns">
</mtx-grid>`

**Comment by nzbin** [comment]
ng-matero 和 extensions 是两个项目，你需要安装一下，另外建议更新一下 ng-matero

```bash
npm install @ng-matero/extensions --save
```

**Comment by zouchengtao** [comment]
> ng-matero 和 extensions 是两个项目，你需要安装 extensions，另外建议更新一下 ng-matero
> 
> ```shell
> npm install @ng-matero/extensions --save
> ```

好的，谢谢
