### ISSUE TITLE
Grid: mat-badge support in MtxGridColumnButton

### ISSUE THREAD

**Issue by SYS64738** [ng-matero/extensions#237]
Hi, it would be great if MtxGridColumnButton would support mat-badge for a button, with rowData support too, so it could be possible to show badge content data dinamcally.

Thank you very much!

**Comment by nzbin** [comment]
Do you try the custom template?
https://ng-matero.github.io/extensions/components/grid/overview#custom-cell-template-2

**Comment by SYS64738** [comment]
hi, thank you for your quick answer; for sure I suppose that with custom cell template I could resolve (I use currently cell templates in different situations)... but in this case I have a set of buttons in a button type column (in addition with expandable button) and I think a badge support could be useful, as you already support pop, etc... thank you!!!

**Comment by nzbin** [comment]
The new version [16.1.0](https://github.com/ng-matero/extensions/releases/tag/v16.1.0) has added mat-badge support, it also supported dynamical data.

```ts
columns: MtxGridColumn[] = [
  {
    header: 'operation',
    field: 'operation',
    buttons: rowData => [{ text: rowData.text, badge: rowData.badge }]
  }
]
```

**Comment by SYS64738** [comment]
Thank you very much! it's exactly what I need. Unfortunately I couldn't use it immediately, due I cannot upgrade my projects to Angular 16 at the moment. 
I suppose you don't make available this feature in the last 15.x ng-matero/extensions.
Have a nice day!

**Comment by nzbin** [comment]
Now the v15 has supported mat-badge, please have a try.

**Comment by SYS64738** [comment]
hi @nzbin! you're super!!! it works fine, just an aesthetic issue: in case of standard row height, badge is hidden by previous row, as you can see:

![image](https://github.com/ng-matero/extensions/assets/1895888/4f078141-3a4d-46dd-a76e-84eeff72a8a0)

thanks a lot!

**Comment by nzbin** [comment]
Because there has no enough space to display the badge. You can customize the badge with its config.

https://github.com/ng-matero/extensions/blob/cd3cdff602defcb42d628aaaf78c77c4749948c8/projects/extensions/grid/interfaces.ts#L125-L134

```ts
columns: MtxGridColumn[] = [
  {
    header: 'operation',
    field: 'operation',
    buttons: rowData => [{ 
      text: rowData.text, 
      badge: {
        content: rowData.badge,
        size: 'small',
        overlap: true
      }
    }]
  }
]
```
Another way, you can also modify the `padding` of `table td`
```css
.mtx-grid .mat-mdc-cell {
  padding-top: 16px;
  padding-bottom: 16px;
}
```

**Comment by SYS64738** [comment]
thank you for your quick reply. I'd already configured badge similar to your example (I also tried small size but it's not enough).

so I try your suggestion changing td padding, but the only way I found to get any results is this:

::ng-deep .mtx-grid .mat-mdc-cell {
  padding-top: 16px !important;
  padding-bottom: 16px !important;
}

(I don't want to set padding in the global style-sheet, since I use badge in a very few tables).

this is the result, badge now is properly shown, but padding affects the expansion row (that contains colspan cell); I'm not a super expert in css, maybe there's a way to avoid this...

![image](https://github.com/ng-matero/extensions/assets/1895888/c4a923f0-89df-4998-8469-8741a67fd223)

**Comment by nzbin** [comment]
I have updated the following example, you can check the styles what I wrote.
https://ng-matero.github.io/extensions/components/grid/overview#row-with-buttons
<img width="181" alt="image" src="https://github.com/ng-matero/extensions/assets/20625845/1de85caf-d668-4ab9-9f36-bc64b7befae9">

**Comment by SYS64738** [comment]
now looks perfect! thank you so much!

![image](https://github.com/ng-matero/extensions/assets/1895888/12806ca7-b7fe-4622-ab70-d8c59044e105)
