### ISSUE TITLE
Position issue with Firefox

### ISSUE THREAD

**Issue by autonomobil** [ng-matero/extensions#238]
Something goes wrong when using Firefox and the dropdown selection from https://ng-matero.github.io/extensions/components/select/overview. Drop down list appears at the bottom of the page, instead of where it belongs. Dropdown is set to extended in the following images:

![image](https://github.com/ng-matero/extensions/assets/31781343/e10d38b9-dfd4-43bd-ab62-ef70f7fb270b)
![image](https://github.com/ng-matero/extensions/assets/31781343/50646180-0c4f-4625-875e-f00453b7097f)
![image](https://github.com/ng-matero/extensions/assets/31781343/12d9654e-4ec8-41ac-9e50-23e8a37c9dd5)

Ubuntu 22.04
Firefox 115.0.2 (installed via flatpak)

**Comment by nzbin** [comment]
Thanks for your advice, I have fixed this issue which caused by `appendTo` prop.

**Comment by autonomobil** [comment]
Thanks for fixing :)
