### ISSUE TITLE
請問一下如何獲取gird展開按鈕點擊事件和狀態？

### ISSUE THREAD

**Issue by Sanotsu** [ng-matero/extensions#24]
目前就是我需要在每行點擊keyboard_arrow_right按鈕時獲取到指定欄位某一值，再去后臺查詢相關數據，然后把新查詢的結果顯示在展開的template中。

所以我想能否在expandable=true的時候，獲取到該展開合并的按鈕事件去觸發查詢和顯示，煩請指導，謝謝。

**Comment by nzbin** [comment]
`(expansionChange)="log($event)"`，参考 [Expandable Row Demo](https://ng-matero.github.io/extensions/data-grid#expandable-row)，打开控制台查看传参

**Comment by Sanotsu** [comment]
@nzbin 感謝指導。
