### ISSUE TITLE
DateTimeAdapter for dayjs

### ISSUE THREAD

**Issue by DerHerrGammler** [ng-matero/extensions#240]
This library is currently missing datetime format support for dayjs datetime formats, could we add this?

I think since dayjs is way smaller than luxon and date-fns it would be great to have the option to use dayjs.

**Comment by nzbin** [comment]
Thanks for your advice, there has already a discussion https://github.com/ng-matero/extensions/discussions/146 about this issue.
Because this library is built above Angular Material, so I will add dayjs adapter after Angular Material does.
