### ISSUE TITLE
Error when using Datetimepicker provided in a library

### ISSUE THREAD

**Issue by SYS64738** [ng-matero/extensions#241]
Hi, I used Datetimepicker in a projects deployed as a library; when I run app directly in library projects all works fine; when I build the library and try to use my component (that contains a Datetimepicker) a strange error occurs.

![image](https://github.com/ng-matero/extensions/assets/1895888/20e36872-9784-47bc-9c2f-587d8ad9c0fe)

![image](https://github.com/ng-matero/extensions/assets/1895888/f272a4af-3c63-4fdd-9130-8c8d5d68b0b9)

![image](https://github.com/ng-matero/extensions/assets/1895888/dab75cd6-e8cd-4e9d-96e8-73bc5d1f603f)

![image](https://github.com/ng-matero/extensions/assets/1895888/2fde3525-a556-4f5f-96ac-6557aa6a9178)

If I use standard Material mat-datepicker instead of mtx-datetimepicker, without changing anything else, all works fine...

Thank you very much for any suggestion and have a nice day

**Comment by nzbin** [comment]
I'm not sure what the reason and I hope you can give me on online example.

**Comment by SYS64738** [comment]
for sure I can provide you what you need. It's not so easy to provide current project, the library contains a very big form, with many sections.

I'll try to arrange a little application, then I'll inform you.

thank you

**Comment by SYS64738** [comment]
preparing an example for you, I made a deep check: I start to build an empty app that used only my lib with Datetimepicker, and it works fine.

then I start adding, one by one, remaining high level deps, until I find that one of our custom lib, when added as deps to main app, would cause the error.

in fact, that library would importing MatNativeDateModule instead of MatMomentDateModule (even if doesn't use dates at all); moving the import  to MatMomentDateModule has resolved the issue.

resuming, I was start in this situation:

my_custom_lib_1 (with Datetimepicker) -> import MatMomentDateModule
my_custom_lib_2 (without Datetimepicker) -> import MatMomentDateModule
my_custom_lib_3 (without Datetimepicker and dates at all) -> Import MatNativeDateModule

my_main_app -> import lib_1, lib_2, lib_3 and MatMomentDateModule -> ERROR!

removing MatNativeDateModule deps and adding MatMomentDateModule (since I use the same Material module set everywhere), all works fine... I forgot to migrate some times ago that library to Moment...

sorry for wasting time, I hope this could be useful for other people...

have a nice weekend!

**Comment by jcachat** [comment]
@SYS64738 I have been pulling my hair out for 2 days on the exact same issue.  I finally came across this post, did a search in my project, and found the exact same issue - someone had imported MatNativeDateModule for no reason.  THANK YOU for posting and following up with your solution!  It solved my issue too.

If it helps anyone else, I was getting either or both of these errors:
TypeError: (intermediate value).createDate(...).format is not a function
Circular dependency in DI detected for DatetimeAdapter.

**Comment by SYS64738** [comment]
> @SYS64738 I have been pulling my hair out for 2 days on the exact same issue. I finally came across this post, did a search in my project, and found the exact same issue - someone had imported MatNativeDateModule for no reason. THANK YOU for posting and following up with your solution! It solved my issue too.
> 
> If it helps anyone else, I was getting either or both of these errors: TypeError: (intermediate value).createDate(...).format is not a function Circular dependency in DI detected for DatetimeAdapter.

you're welcome! I'm happy to have been helpful :)
