### ISSUE TITLE
mtx-grid sorting with "complex" field seems doesn't work

### ISSUE THREAD

**Issue by SYS64738** [ng-matero/extensions#243]
hi, when I have a field that refers a subfield in a complex object, data are shown fine, but sorting on column seems doesn't work.

this is an example of configuration:

![image](https://github.com/ng-matero/extensions/assets/1895888/cb38c52f-1d8a-4066-97fa-9103d758be40)

thank you,
have a nice day

**Comment by SYS64738** [comment]
this is the main object (I pass an array of this kind of objects to mtx-grid data)

![image](https://github.com/ng-matero/extensions/assets/1895888/38d4a051-f48f-43e1-8ee9-a58e30b712e3)

the Family object looks like:

![image](https://github.com/ng-matero/extensions/assets/1895888/d051e498-3d45-4e8d-b625-5d3476cabf25)

**Comment by nzbin** [comment]
I'm sorry, the sort doesn't support nested object. Maybe you can try to customize the `sortingDataAccessor` https://github.com/ng-matero/extensions/discussions/135

**Comment by SYS64738** [comment]
I tried to use sortingDataAccessor, without success... the strange behavior I noticed is: if I sort the grid by any "non-nested" object, then (only the first time) sort works even with any other nested object; this behavior occurs even if I don't use sortingDataAccessor, it occurs always...
