### ISSUE TITLE
(data-grid) Feature request: Add button type 'link'

### ISSUE THREAD

**Issue by dragermrb** [ng-matero/extensions#245]
Hi!

Regarding the `data-grid` component, I would like to be able to have links as column buttons instead of buttons, that is, a button type `'link'` that generates an anchor tag (`<a ...>`) instead of a button tag (`<button ...>`)

The reason is to be able to open the links in a new tab if the user needs it (for example by clicking on a link with the central mouse button). This behavior is not possible with `<button>` tags.

Would you accept a PR that implemented such functionality?

**Comment by nzbin** [comment]
There already has a link type for column.

```ts
columns: MtxGridColumn[] = [
  {
    header: 'anchor',
    field: 'anchor',
    type: 'link',
  },
]
```
Or you can also use custom template.
https://ng-matero.github.io/extensions/components/grid/overview#custom-cell-template-2

**Comment by dragermrb** [comment]
Hi @nzbin 

I was thinking of having several buttons/links in the same cell. For example two links (view, edit) and one delete button (with confirmation).

![Screenshot_20231004_123611](https://github.com/ng-matero/extensions/assets/11479696/e01a884d-aa0c-4232-83d0-980e72871edf)

I'm currently using custom templates, but I think it might be useful to have link type buttons.

**Comment by nzbin** [comment]
As your demand, you can use the API `window.open` instead of `a` link.

**Comment by dragermrb** [comment]
If I use `window.open` the links always opens in a new window.

With a normal `a` link, the user can navigate in the same window or open the destination in a new one (context menu->open in new tab or with the middle mouse button).

**Comment by nzbin** [comment]
> If I use window.open the links always opens in a new window.

```js
open()
open(url)
open(url, target)
open(url, target, windowFeatures)
```
https://developer.mozilla.org/en-US/docs/Web/API/Window/open#parameters

As your image shows, I think the `view` and `edit` button should navigate a new route, it's better to use Angular Router (`this.router.navigate()`) instead of `open()`.

With lots of projects I do, I don't use `a` link yet. If you really need a link, please use the custom template.

**Comment by dragermrb** [comment]
Thanks @nzbin
