### ISSUE TITLE
Mtx-Grid allow row to selected if press only on checkbox

### ISSUE THREAD

**Issue by hanogin** [ng-matero/extensions#249]
Right now if i add rowSelect option the row selected if i press anywhere at the row, what if i only whant to copy paste some text in the row, or press other button - the row immediately got selected.

It would be nice if we can select the row only by click on the check box, exactly likt the solution suggest in this link
https://stackoverflow.com/questions/58424894/angular-material-how-to-select-table-row-by-clicking-only-the-checkbox

**Comment by nzbin** [comment]
```html
<mtx-grid [disableRowClickSelection]="true"></mtx-grid>
```
