### ISSUE TITLE
请问下怎么设置mtx-grid里图片的大小？还有为什么图片点击没反应，demo里是可以放大的

### ISSUE THREAD

**Issue by zouchengtao** [ng-matero/extensions#25]
`{ header: '图片', field: 'cutterImg', type: 'image', width: "120px"},`

**Comment by nzbin** [comment]
需要手动引入 photoviewer 的样式，这一块之后再优化一下，其实可以自己利用模板实现大图功能
```scss
@import '~photoviewer/dist/photoviewer.css';
```

**Comment by zouchengtao** [comment]
> ```css-scss
> @import '~photoviewer/dist/photoviewer.css';
> ```

好的，那怎么设置表格里图片大小呢

**Comment by nzbin** [comment]
图片大小可以通过 css 设置，如果还有比较特殊的需求，建议使用自定义单元格

**Comment by zouchengtao** [comment]
> 定义
好的，谢谢🙏
