### ISSUE TITLE
How to disable animation

### ISSUE THREAD

**Issue by corentinclichy** [ng-matero/extensions#256]
I would like to disable animation on the drawer.

Is it possible ? 
Do you think that we can add this option (like the `@disable` from angular)? 
This animation create visual bug on the ui on my side. 

EDIT:

to give a bit more context, here is the bug I have if I disable all angular animation with NoopAnimationModule I don't get any bug anymore.
Note that the bug is only on chrome.
![image](https://github.com/ng-matero/extensions/assets/8075501/44e7823d-07bb-4a03-bb49-c39cb6e0e9e7)

thanks in advance

**Comment by nzbin** [comment]
Can you give me an online example?

**Comment by corentinclichy** [comment]
mmm I can't as the application I have is protected with proxy. 

I did a lot of test, I guess is when there is a graph underneath (I use chartjs on this project)

I did a PR to add a "disableAnimation" option to the drawer component.

I guess it can be a great feature to have on your component, for this kind of situation but mainly for performance optimisation and accessibility.

**Comment by nzbin** [comment]
I hope you can give me a minimal reproduce demo and I want to know how you use it. I don't think it is the animation caused this issue.

**Comment by nzbin** [comment]
I'm sorry, I will close this issue as you can't provide a minimal reproduce demo.
