### ISSUE TITLE
Upgrade to angular 17 gives a crash

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [ng-matero/extensions#259]
<img width="1080" alt="image" src="https://github.com/ng-matero/extensions/assets/1098243/49ace33d-b2c6-42ba-bad9-2418ef2c016c">

Possibly this is related to =>
<img width="622" alt="image" src="https://github.com/ng-matero/extensions/assets/1098243/7c8c60be-0d82-4edc-9337-43d567c65eac">

?

**Comment by nzbin** [comment]
v17 has released, please have a try.

**Comment by LanderBeeuwsaert** [comment]
@nzbin upgraded and works, thanks!
