### ISSUE TITLE
Disabled button in mtx-grid

### ISSUE THREAD

**Issue by Huuvinh94** [ng-matero/extensions#26]
I have column with file `option` and type `button`, as shown below:

![image](https://user-images.githubusercontent.com/18391623/86202261-f8f6e600-bb8b-11ea-9aa6-30258441973c.png)

How to disabled button?

Please help me?
Thanks a lot.

**Comment by nzbin** [comment]
It doesn't support disabled button in column config yet, you can customize buttons with `cellTemplate`

**Comment by Luperco** [comment]
> It doesn't support disabled button in column config yet, you can customize buttons with `cellTemplate`

Unfortunately it is static. Cannot disable if an external event (for example after got data from server) tell me that should be disabled.

Any other suggestions?

Thanks.

**Comment by nzbin** [comment]
> > It doesn't support disabled button in column config yet, you can customize buttons with `cellTemplate`
> 
> Unfortunately it is static. Cannot disable if an external event (for example after got data from server) tell me that should be disabled.
> 
> Any other suggestions?
> 
> Thanks.

```html
<mtx-grid [data]="list"
          [columns]="columns"
          [cellTemplate]="{operation: operationTpl}">
</mtx-grid>

<ng-template #operationTpl let-row let-index="index" let-col="colDef">
  <button [disabled]="disabled_condition">{{row}}</button>
</ng-template>
```

**Comment by Luperco** [comment]
Thank you, I'll give it a try.

**Comment by Luperco** [comment]
I use the pop and popTitle feature of the command column, like this:

`  tableButtons: MtxGridColumn = {
    header: 'Operation',
    field: 'operation',
    width: '160px',
    pinned: 'right',
    right: '0px',
    type: 'button',
    buttons: [
      {
        type: 'icon',
        text: 'delete',
        icon: 'attach_file',
        click: record => this.openFileUploader(record),
      },
      {
        type: 'icon',
        text: 'edit',
        icon: 'edit',
        click: record => this.edit(record),
      },
      {
        type: 'icon',
        text: 'delete',
        icon: 'delete',
        color: 'warn',
        pop: true,
        popTitle: 'Confirm delete?',
        click: record => this.delete(record),
      },
    ],
  };
`

Is there a way to replicate with cellTemplate?

Thanks.

**Comment by Luperco** [comment]
Nevermind. I was able to figure by myself. I had to write my popup confirmation (with MtxDialog.confirm()) and use mat-button-icon for icons.
Thank you anyway.

**Comment by ismailix** [comment]
buttons: [
        {
          type: 'icon',
          icon: 'edit',
          tooltip: this.translate.stream('organizations.edit'),
          click: record => this.edit(record),
        },


  edit(value: any) {
    const dialogRef = this.dialog.originalOpen(LicencesEditComponent, {
      width: '600px',
      data: { record: value },
    });

    dialogRef.afterClosed().subscribe(() => console.log('The dialog was closed'));
  }


how can I disable them and open ORGANIZATIONEDITCOMPONENT

**Comment by nzbin** [comment]
@ismailix You mean disable the button?
https://ng-matero.github.io/extensions/components/grid/overview#row-with-buttons

**Comment by ismailix** [comment]
@nzbin when I click on this button, it should not open in the dialog window, but instead I want a new window to open
