### ISSUE TITLE
bump angular 17

### ISSUE THREAD

**Issue by damingerdai** [ng-matero/extensions#261]

**Comment by damingerdai** [comment]
*@ngx-translate/core*: [ngx-translate#1455](https://github.com/ngx-translate/core/issues/1455)

**Comment by damingerdai** [comment]
@ng-select/ng-select  support angular in [ng-select#2296](https://github.com/ng-select/ng-select/pull/2296)

**Comment by damingerdai** [comment]
ngx-color: [ngx-color#379](https://github.com/scttcper/ngx-color/issues/379)

**Comment by damingerdai** [comment]
ngx-progressbar: [ngx-progressbar#364](https://github.com/MurhafSousli/ngx-progressbar/issues/364)

**Comment by damingerdai** [comment]
@nzbin please preview

**Comment by A77AY** [comment]
@nzbin Please publish version 17, maybe as an RC?

**Comment by nzbin** [comment]
@A77AY There's a lot of work to be done and I'm very busy with my work recently. Maybe v17 will be released next month.

**Comment by nzbin** [comment]
v17 has released.
