### ISSUE TITLE
mtx-grid avoid specific column to be "hideable"

### ISSUE THREAD

**Issue by SYS64738** [ng-matero/extensions#264]
Hi, I'm using [columnHideable] with corresponding menu to hide/show the columns. 

Typically I use the first column in table as "action" column (with buttons, expandable, etc...), so I woulnd't permit to hide this column.

There's a way to avoid that a column (some columns) could be hide ? a kind of "lock" of visibility column (as like as "sortable", "resizable", etc...).

Thank you very much!
Roberto

**Comment by nzbin** [comment]
```ts
columns: MtxGridColumn[] = [
  {
     ....
     disabled: true,
  }
]
```

**Comment by SYS64738** [comment]
Thanks! It works fine about hiding/showing column. 

It would be great if there's a way to avoid moving column too (I suppose disabled flag could be use for both behavior): in fact an "action" column with button, expandable arrow, etc... should be in a fixed position (at start or end of a row); I already set "pinned = 'left'" but the coulumn could be moved and "overtake" by other columns.

Good: 
![image](https://github.com/ng-matero/extensions/assets/1895888/8bb505ee-0836-4978-b904-c2a518994d84)

Not so good ;-)
![image](https://github.com/ng-matero/extensions/assets/1895888/c6e23ad4-806f-4087-9dda-302a913e0b4f)

Thank you!!!

**Comment by nzbin** [comment]
> I think the best solution should be: if a column has pin left or right and has disabled flag = true, no other “floating” columns could overtake it and that column couldn’t be moved.

It's very hard to implement, I hope someone can provide a PR.

**Comment by hanogin** [comment]
@nzbin 
I have a few column that i do not want to be hide nor moved, i want them show and in the initial order all the time.
How about if a column has a diable flag (or some other name flag) then in that case we do not not showing it at all on the menu, is it hard to implement as well?
