### ISSUE TITLE
MtxDrawer cannot scroll inside component sometimes in mobile

### ISSUE THREAD

**Issue by CeloGomesBR** [ng-matero/extensions#266]
I really don´t know what is happen with it.  In computer it´s ok, but in many smartphones the sidebar with overflow content cannot be scrolled.  The scroll act on body (besides overlay) or do nothing.  My website is totally based on sidebars.  
It´s driving me crazy..
I´m using Angular 17 and angular material 17.
I chosed your component because I use your Drawer in all positions, and Material Design only have left position.

Could you help me?? All users of my website are complaining about it.

Thanks in advance!

**Comment by nzbin** [comment]
I tested with iPhone 14 pro max and I don't find any issues.
