### ISSUE TITLE
mtxPopover, can i hide popover direction arrow dynamically?

### ISSUE THREAD

**Issue by peterxakia** [ng-matero/extensions#269]
First of all, thank you for awsome library. I have used mtx popover a lot.
Got a question, is it possible to hide mtx-popover-direction-arrow dynamically?
![image](https://github.com/ng-matero/extensions/assets/141605629/fad89a68-1996-435e-b353-396ca255b7b3)

**Comment by nzbin** [comment]
The new version 16.3.0 added a new option `hideArrow`, please have a try.
https://ng-matero.github.io/extensions/components/popover/overview
