### ISSUE TITLE
mtx-grid, column with fixed width will be resized anyway

### ISSUE THREAD

**Issue by SYS64738** [ng-matero/extensions#270]
hi, 

I have a grid with MtxColumns defined dynamically by user; I assign columns in ngAfterViewInit() method and all works fine except one thing:

I have the first column with this settings:

```
actionColumn: MtxGridColumn =
    {
      field: 'action',
      header: 'Azioni',
      pinned: 'left',
      disabled: true,
      left: '0px',
      width: '210px',
      minWidth: 210,
      type: 'button',
      showExpand: true,
      resizable: false,
...
```

then a list of default columns (the basic case):

```
defaultColumns: MtxGridColumn[] = [
    { header: 'Nosologico', field: 'nosologico', sortable: true },
    { header: 'Data ricovero', field: 'dataRicovero', sortable: true },
    { header: 'Data dimissione', field: 'dataDimissione', sortable: true },
...

```
in ngAfterViewInit() I do:

```
...
this.grid.columns = [this.actionColumn, ...this.defaultColumns];
...

```

when columns exceed the witdth of grid (creating the horizontal scroollbar), the first column will be resized too, despite I set a fixed witdth; as soon I resize a column the width of the first will be fixed back and looks good.

even if I add / remove column with columnMenuButton the same unwanted resize occurs.

wrong behavior (action button column width about 114px): 
![image](https://github.com/ng-matero/extensions/assets/1895888/8afa084b-62f9-4558-b5b3-0184102b14d7)

right behavior (action button column width = 210px:
![image](https://github.com/ng-matero/extensions/assets/1895888/81f8d4cd-1e27-4f14-a479-41c35d5989cd)

It seems a kind of missing refresh issue...
Thank you very much,
r.

**Comment by nzbin** [comment]
Can you provide an online example?

**Comment by SYS64738** [comment]
of course, here i wrote a simple Stackblitz project; I suspect the issue occurs when "resizable = true" on MtxGrid, even if a specific column (action in my case) is set to "resizable = false"

https://stackblitz.com/edit/angular-tqpzbd?file=src%2Fapp%2Fapp.component.ts

**Comment by nzbin** [comment]
https://stackblitz.com/edit/angular-n9apwr?file=src%2Fapp%2Fapp.component.ts

```diff
actionColumn: MtxGridColumn = {
   field: 'action',
   header: 'Azioni',
   pinned: 'left',
   disabled: true,
   left: '0px',
-  width: '210px',
   minWidth: 210,
+  maxWidth: 210,
   type: 'button',
   showExpand: true,
-  resizable: false,
   ...
}
```
In fact, the resizable feature is only the Angular Material experimental feature.
