### ISSUE TITLE
[Bug] [Mtx-Select] Events stopped working

### ISSUE THREAD

**Issue by marcelimati** [ng-matero/extensions#271]
Version [v16.1.3](https://github.com/ng-matero/extensions/releases/tag/v16.1.3)  is last version that event is firing.

Both versions: [v16.2.0](https://github.com/ng-matero/extensions/releases/tag/v16.2.0) and [v16.3.0](https://github.com/ng-matero/extensions/releases/tag/v16.3.0) 

Events like (change) and (clear) - probably all others too stopped working

```
<-- html file -->
<mtx-select [items]="items" formControlName="person" bindLabel="name" bindValue="id" (change)="log($event)" (clear)="log(event)"></mtx-select>

<-- ts file -->
log(event: any) {
    console.log(event) // fires always undefined
}
```

**Comment by nzbin** [comment]
16.3.1 has fixed this issue.

**Comment by marcelimati** [comment]
It works now, thanks.
