### ISSUE TITLE
Crash when MtxPopoverModule isn't present in app.module 

### ISSUE THREAD

**Issue by TiagoMAGarcia** [ng-matero/extensions#272]
If the MtxPopoverModule isn't present in app.module there is crash even though it is present on the module of one of the routes

![image](https://github.com/ng-matero/extensions/assets/73131074/d992e4da-b760-41c8-925c-ca13c78a8e1b)
![image](https://github.com/ng-matero/extensions/assets/73131074/78d44fc1-3184-4640-92a1-df045d33daa5)

### Environment
Angular CLI: 17.1.0-next.3
Node: 20.10.0
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 17.0.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                              Version
--------------------------------------------------------------
@angular-devkit/architect            0.1701.0-next.3
@angular-devkit/build-angular        17.1.0-next.3
@angular-devkit/core                 17.0.6
@angular-devkit/schematics           17.0.6
@angular/cdk                         17.0.4
@angular/cli                         17.1.0-next.3
@angular/fire                        17.0.0
@angular/google-maps                 17.0.4
@angular/material                    17.0.4
@angular/material-date-fns-adapter   17.0.4
@angular/youtube-player              17.0.4
@schematics/angular                  17.0.6
rxjs                                 7.8.1
typescript                           5.2.2
zone.js                              0.14.2

**Comment by nzbin** [comment]
I create an online example and I don't find any issues. Can you provide an online example?
https://stackblitz.com/edit/angular-ivy-hph2hn?file=src%2Fapp%2Fapp.component.ts
