### ISSUE TITLE
[Grid] re-render data with custom (dynamic) class on columns

### ISSUE THREAD

**Issue by SYS64738** [ng-matero/extensions#276]
Hi, I have a grid with a dynamic class on columns:

```
highLitedColumns: string[] = [];
...
class: (data: any, colDef: MtxGridColumn | undefined) => !!colDef && this.highlitedColumns.includes(colDef.field) ? 'success : ''
...
```

there's a way to re-evaluate (render) the grid when something change in highLitedColumns array ? it works only if I reload data (or move to next page).

I mean a behavior like "ngClass".
I already try this.grid.table.renderRows() without success.

Thank you very much!

**Comment by nzbin** [comment]
Can you provide an online example?

**Comment by SYS64738** [comment]
of course, here is an example.

btw: the same occurs with rowClassFormatter (I included it in the example); if class condition change after first render nothing happens, it seems that classes are evaluated once by render.

https://stackblitz.com/edit/angular-tqpzbd?file=src%2Fapp%2Fapp.component.ts

thank you!

**Comment by nzbin** [comment]
I forked the example and update it, please check the comments.
https://stackblitz.com/edit/angular-4x4ryo?file=src%2Fapp%2Fapp.component.ts

> it seems that rowHover is always enabled on it

For Material >= 15, it has a redundant hover state style, you should fix it by yourself. I only fixed this issue above v16.
