### ISSUE TITLE
Datetimepicker Actions button in date view?

### ISSUE THREAD

**Issue by FabianWenzel** [ng-matero/extensions#281]
Is there a possibility or workaround in having the actions buttons also available in the date view? Appreciate any hints :)

**Comment by nzbin** [comment]
@CnxYankoNikolov I will be glad if you can provide a PR.

**Comment by CnxAtanasIliev** [comment]
@nzbin This can be closed at some point. Don't know if you close them after release or after merge . Thanks.

**Comment by nzbin** [comment]
18.1.0 has released, please have a try.
