### ISSUE TITLE
Fixed Header table in mtx-grid

### ISSUE THREAD

**Issue by SezarMAB** [ng-matero/extensions#282]
I want to make the header fixed while scrolling through a long table:

![image](https://github.com/ng-matero/extensions/assets/49267000/fb471f6d-776d-47b4-8e43-200f0fdb0eeb)

How to do it in mtx-grid?

thanx!

**Comment by nzbin** [comment]
Please check this example
https://ng-matero.github.io/extensions/components/grid/overview#column-resize
