### ISSUE TITLE
[mtxPopover] ERROR TypeError: Cannot read properties of undefined (reading 'listen')

### ISSUE THREAD

**Issue by InYourHead** [ng-matero/extensions#291]
I found issue, when mtxPopover is on link used to redirect to another page.

I creaded full example with cypress tests.

How to reproduce it?

1. clone repository:

https://github.com/InYourHead/mtx-popover-error-example/tree/master

2. Install node 16+

3. Run ```npm install```

4. Run ```npm run start``` to start sample application

5. In another terminal run ```npx cypress open ```

6. Start E2E Testing and select chrome and follow given steps:

![Zrzut ekranu z 2024-03-22 10-39-16](https://github.com/ng-matero/extensions/assets/11540730/bdb9f31c-c7fe-483c-9a26-5e32b3e3c8e7)

![Zrzut ekranu z 2024-03-22 10-39-50](https://github.com/ng-matero/extensions/assets/11540730/8939824d-8d7f-4827-b75b-43aa87a72cbd)

![Zrzut ekranu z 2024-03-22 10-41-13](https://github.com/ng-matero/extensions/assets/11540730/3671fae1-3d5d-4d4c-8b16-6b42bee3de2f)

**7. After executing tests in console you can see given error:**

![Zrzut ekranu z 2024-03-22 10-41-57](https://github.com/ng-matero/extensions/assets/11540730/a1cac8b2-f412-4ab8-b36b-8b0d0252e4b2)

```
VM144:1 ERROR TypeError: Cannot read properties of undefined (reading 'listen')
    at TransitionAnimationEngine.listen (browser.mjs:3428:20)
    at InjectableAnimationEngine.listen (browser.mjs:4353:39)
    at AnimationRenderer.listen (animations.mjs:342:32)
    at listenerInternal (core.mjs:15641:40)
    at ɵɵlistener (core.mjs:15522:5)
    at MtxPopover_ng_template_0_Template (mtxPopover.mjs:461:1318)
    at executeTemplate (core.mjs:12126:9)
    at renderView (core.mjs:11948:13)
    at TemplateRef.createEmbeddedView (core.mjs:23041:9)
    at ViewContainerRef.createEmbeddedView (core.mjs:23159:37)
```

It propably indicates, that animation cannot be execute after view change. It is problematic, when your application has global error handling.

**Affected version: @ng-matero/extensions:14.8.2**

**Comment by InYourHead** [comment]
Any updates on current progress? I can try to fix it, but this code is quite complex.

**Comment by nzbin** [comment]
Sorry for late reply.

https://github.com/InYourHead/mtx-popover-error-example/blob/master/src/app/simple-button/simple-button.component.html

Please remove the `routerLink` and test again, the error will be gone.

**Comment by InYourHead** [comment]
Is it possible to use it with routerLink? I need to navigate users after click.

**Comment by nzbin** [comment]
> Is it possible to use it with routerLink? I need to navigate users after click.

I'm sorry, the error only can be found with e2e test and I don't know what happened. I haven't enough time to explore the cypress.

**Comment by alexciesielski** [comment]
this still happens in the latest version in our production app (not in e2e). unfortunately I cannot pinpoint the exact HTML that causes it but I believe we are not using mtxPopover on any routerlink element

**Comment by InYourHead** [comment]
I managed to fix this issue.

1. [Broken version](https://github.com/InYourHead/mtx-popover-error-example/tree/broken)
2. [Fixed version](https://github.com/InYourHead/mtx-popover-error-example/tree/fixed)

To run the fixed version you need to:
1. clone git repository from branch: https://github.com/InYourHead/extensions/tree/17.3.x-animations 
2. build the project using yarn
3. replace <path-to-mtx-popover-dist> with your repository location in package.json
4. npm install && npm run

After applying this change, the error no longer occurs in the console.

What was the main issue?

` (@transformPopover.start)="_onAnimationStart($event)"` -> this listener was triggered when the object no longer existed in view.

More details:

`setTimeout` causes this bug, to avoid it when destroying MtxPopover, you must set flag `_halt` to true to prevent opening a modal
```
  /** Handles mouse enter on the trigger. */
  _handleMouseEnter(event: MouseEvent): void {
    this._halt = false;

    if (this.popover.triggerEvent === 'hover') {
      this._mouseoverTimer = setTimeout(() => {
        this.openPopover();
      }, this.popover.enterDelay);
    }
  }
```

**Comment by InYourHead** [comment]
@nzbin please, reopen this issue and let me know if anything is unclear

**Comment by InYourHead** [comment]
@nzbin should I cherry pick it to other branches?

**Comment by nzbin** [comment]
> @nzbin should I cherry pick it to other branches?

You can update it to v16 and v18. No longer supported below v16.

**Comment by nzbin** [comment]
@InYourHead `v17.3.6` and `v18.2.1` has released, please have a try.

**Comment by InYourHead** [comment]
I created PR to 16.x

**Comment by InYourHead** [comment]
It looks like the issue is fixed. I'm closing it. @nzbin thx for help. @alexciesielski it may resolve your problem too.
