### ISSUE TITLE
feat(Datetimepicker): Dots between minutes

### ISSUE THREAD

**Issue by angelaki** [ng-matero/extensions#296]
Coming from the deperected https://github.com/IliaIdakiev/angular-material-timepicker, I'd love to see dots for the minutes. Looks just great imho:

![image](https://github.com/ng-matero/extensions/assets/38611461/c65b36f9-a3f7-4bb4-8351-c59fdf3643fb)

**Comment by nzbin** [comment]
Can you show the Material Design Spec for this feature?

**Comment by angelaki** [comment]
> Can you show the Material Design Spec for this feature?

Hmm, oh, no. Guess there actually is none. Didn't know, that you kept the lib super close to the Material Design Specs. But good to know!
