### ISSUE TITLE
call a function from MtxGridColumn

### ISSUE THREAD

**Issue by VinitVishwanathan** [ng-matero/extensions#3]
I have a column which is a link. want to add a click event in that.
 format: (data: any) => { return `<a (click)="callfunction()" >${data.Status} </a>`; }
tried this, but the function is not getting called. What am I  doing wrong?

I also tried keeping it a button. It worked but the text was not displayed. Is Icon mandatory in Grid button. can't we keep text only? The text should change dynamically as shown in the format. Is that possible?
```js
 {
      title: 'Status',
      index: 'Status',
      type: 'button',
      fixed: 'left',
      width: 'auto',
      sort: true,
      checked: true,
      disabled: false,
      buttons: [
        {
          icon:null,
         text:'abc',
          tooltip: 'Edit Template Attribute',
          type: 'link',
          click: ()=>{alert("hi")},
        }]
      // format: (data: any) => { return `<a (click)="onGoToPage2()">${data.Status} </a>`; }
    }.
```

Thanks in advance

**Comment by nzbin** [comment]
@VinitVishwanathan I have refacted the data grid, you can view the [demos](https://ng-matero.github.io/extensions/data-grid).

**Comment by VinitVishwanathan** [comment]
Thanks a lot..
