### ISSUE TITLE
[Feature Request] Calendar Header Customization

### ISSUE THREAD

**Issue by CnxYankoNikolov** [ng-matero/extensions#302]
I was wondering if the DateTimePicker can support a custom component input for the header part of the calendar, kind of like the Angular Material Component does and if none is passed it fallbacks to the current behavior. 

https://material.angular.io/components/datepicker/api#MatDatepicker for reference.

I am willing to put in a PR if that is something that the maintainers are willing to accept as I kind of need it for my project.

**Comment by nzbin** [comment]
Many thanks for your PR, I will publish tonight.
