### ISSUE TITLE
[MtxSelect] Label not clickable

### ISSUE THREAD

**Issue by andreanaFelicione** [ng-matero/extensions#304]
I noticed that the label can only be clicked for multiple selects, while clicking on the label text has no effect on single selects.
An example [here](https://stackblitz.com/edit/stackblitz-starters-xjt8jg?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Ftest%2Ftest.component.html,src%2Ftest%2Ftest.component.ts,src%2Fmain.ts,package.json,src%2F_variables.scss,angular.json&template=node&title=Angular%20Starter).

**Comment by nzbin** [comment]
<img width="432" alt="image" src="https://github.com/ng-matero/extensions/assets/20625845/b41df727-adf4-42fc-ac57-77e930ff708d">

I'm not sure why the mdc-label add `pointer-events: all`. Please override it and try again.

**Comment by andreanaFelicione** [comment]
Perfect! I override it with pointer-events: unset; and it works now.
Thank you
