### ISSUE TITLE
Clock in TouchUI broken

### ISSUE THREAD

**Issue by angelaki** [ng-matero/extensions#307]
The Clock doesn't fit property using TouchUI on wide screens:

![image](https://github.com/ng-matero/extensions/assets/38611461/4c8c9953-a9d0-452e-b48c-c6ede6ba4d1a)
![image](https://github.com/ng-matero/extensions/assets/38611461/aa756e94-ac5c-4292-946f-06e7e90a38ab)

**Comment by nzbin** [comment]
![image](https://github.com/ng-matero/extensions/assets/20625845/b6ed4104-d756-47af-8262-9a7f3b1896e8)
I'm sorry, it's very difficult to determine what the best size of the clock. I think you can customize its style by yourself if your screen is special.
