### ISSUE TITLE
README: add how to use the library with prebuilt theme from Angular Material

### ISSUE THREAD

**Issue by AlexElin** [ng-matero/extensions#309]
Relates to https://github.com/ng-matero/extensions/issues/51

At the moment the startup guide mentions using the following `@use` and `@include` to style components:
![image](https://github.com/ng-matero/extensions/assets/13061803/d3c7088a-34f7-4033-b187-048c847bb8c1).
However. this is applicable to custom theme only.

The guide says nothing on adding the library when the  prebuilt theme from Angular Material is used.

Pls, add the info into the guide

**Comment by nzbin** [comment]
The readme has updated, please take a look.

**Comment by AlexElin** [comment]
@nzbin, looks good, except usage of `@import` which is deprecated according to the [Sass docs](https://sass-lang.com/documentation/at-rules/import/).

Please, replace it with the `@use`

**Comment by nzbin** [comment]
> @nzbin, looks good, except usage of `@import` which is deprecated according to the [Sass docs](https://sass-lang.com/documentation/at-rules/import/).
> 
> Please, replace it with the `@use`

Maybe it's been imported in `style.css`

**Comment by AlexElin** [comment]
Therefore, it would be helpful to provide 2 examples: one for "style.css" and the other for "style.scss".
