### ISSUE TITLE
Angular 18 support

### ISSUE THREAD

**Issue by glenstaes** [ng-matero/extensions#310]
What is the expected time-window for supporting Angular 18? Can we expect some features/changes or will it just be an upgrade of the Angular dependency?

**Comment by JelleBruisten** [comment]
Is there any work on this ongoing?, it's currently a blocker to upgrade to v18 of angular

**Comment by nzbin** [comment]
I'm sorry, I'm very busy with other projects. The v18 will be released this week.

**Comment by siriwasan** [comment]
Thank you for your attention. You're very kind.

Your big fan.

**Comment by nzbin** [comment]
v18 has released, please check the change log.
https://github.com/ng-matero/extensions/releases/tag/v18.0.0
