### ISSUE TITLE
Did v18 still need '@angular/material-experimental'?

### ISSUE THREAD

**Issue by siriwasan** [ng-matero/extensions#316]
I was upgraded to v18 but it has some error.

 @use '@angular/material-experimental' as matx;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^╵

  node_modules/@ng-matero/extensions/core/theming/_definition.scss 5:1  @forward
  node_modules/@ng-matero/extensions/_index.scss 26:1                   @use
  src/styles.scss 5:1                                                   root stylesheet [plugin angular-sass]

when I add '@angular/material-experimental' the error has gone but I am not sure we still need it.

**Comment by nzbin** [comment]
I'm sorry, 18.0.1 has fixed.
