### ISSUE TITLE
[Tooltip] Tooltip animation doesn't show?

### ISSUE THREAD

**Issue by bonnis** [ng-matero/extensions#318]
I have done something like in the following 
```html
<div
  [mtxTooltip]="tooltipTpl"
>
Some content
</div>

<ng-template #tooltipTpl>
  <div *ngIf="foo"> Foo </div>
  <div *ngIf="!foo"> Bar </div>
</ng-template>

```
With this code, the tooltip will show, but it won't have that animation that normal Angular has, which I'm trying to have. I'm on Angular@`14.2.2` and @ng-matero/extensions@`14.8.5`. Anyone has a clue? Thanks!

**Comment by nzbin** [comment]
Can you provide an online example?
