### ISSUE TITLE
[Split Pane] MtxSpliPane - @Input visible v18 stopped working

### ISSUE THREAD

**Issue by matiasfs12** [ng-matero/extensions#320]
Hi,
First of all, thank you very much @nzbin for the libray, much appreciated.

After upgrading to v18, looks like the **MtxSplitPane Input visible: boolean** stopped working.

I tried with Signals / Observable + async pipe / plain variable and seems to be not working, not sure if Angular v18 change detection strategy tweaks might be related.

https://stackblitz.com/edit/stackblitz-starters-5fyrgq?file=src%2Fmain.ts

Thanks in advance.

**Comment by nzbin** [comment]
18.0.3 has fixed.

**Comment by matiasfs12** [comment]
Thanks @nzbin
