### ISSUE TITLE
Theming instructions are incomplete?

### ISSUE THREAD

**Issue by stnor** [ng-matero/extensions#322]
Hi,
I'm using the datetimepicker (extensions 18.0.3) and I had some issues getting the theming to work.

I added this to my styles.scss:

```
  @include mtx.datetimepicker-theme(m3-theme.$light-theme);
```

But I also needed to add the following to my theme.scss to get any mtx-themes included:

```
$light-theme: mat.private-deep-merge-all(
    mat.define-theme($config),
    mtx.define-theme($config),
);
```

1) Is this documented? I must've missed it if so.
2) Perhaps output an error in the scss-processing if its not done?

**Comment by nzbin** [comment]
I'm sorry, the docs haven't updated. You can check the v18 release note to get more details.
https://github.com/ng-matero/extensions/releases/tag/v18.0.0

**Comment by nzbin** [comment]
https://github.com/ng-matero/extensions?tab=readme-ov-file#theming
