### ISSUE TITLE
[Datetimepicker] When enabling ZonelessChangeDetection Datetimepicker doesn't select HOUR

### ISSUE THREAD

**Issue by francobasilico** [ng-matero/extensions#327]
"@ng-matero/extensions": "18.1.1",

Current behaviour:
provide provideExperimentalZonelessChangeDetection(),

```typescript
export const appConfig: ApplicationConfig = {
  providers: [
    provideExperimentalZonelessChangeDetection(),
    provideRouter(
      routes,
      withComponentInputBinding(),
    ),
```

https://github.com/user-attachments/assets/ae67d80f-726e-4cd5-a0a4-b3e06d619366

Expected behaviour: 

https://github.com/user-attachments/assets/c4df5849-0241-44ee-9c77-f52f7a8cc7c0

**Comment by nzbin** [comment]
@JelleBruisten Can you help me to fix this issue?

**Comment by JelleBruisten** [comment]
@nzbin bit busy this month, but I see you did some changes yourself. 👍

**Comment by francobasilico** [comment]
All working now. Tested with 18.1.2
