### ISSUE TITLE
Add aria-controls Attributes to div Inside mtx-select for Improved Accessibility

### ISSUE THREAD

**Issue by sobriquet11** [ng-matero/extensions#328]
Currently, the mtx-select component does not include an aria-controls attribute on the div element inside it. This attribute is crucial for improving the accessibility of the component, as it allows assistive technologies to establish a relationship between the select box and the element it controls (typically the dropdown list).
any chance that you could add this attribute? thank you

**Comment by nzbin** [comment]
I'm sorry, the mtx-select is a wrapper of ng-select, I don't find props for aria-controls attribute.
https://github.com/ng-select/ng-select
