### ISSUE TITLE
Issue with mtx-select and search

### ISSUE THREAD

**Issue by tallesaragao** [ng-matero/extensions#33]
Apparently there is an issue with the `mtx-select` component search functionality. When you type anything and select an option, the label is disappearing. It seems to happen only on mobile devices, and it can be seen on the library documentation website [https://ng-matero.github.io/extensions/select](url).

I recorded my phone screen to show the issue being reproduced, as you can see below:

![WhatsApp-Video-2020-09-02-at-151](https://user-images.githubusercontent.com/28676328/92021467-3284d280-ed30-11ea-8353-bf2d4e1d6238.gif)

**Comment by nzbin** [comment]
Thanks for your issue. It's ok on iOS, maybe it's a bug on Android with a particular version. Can you tell me more information about your phone and Android version?

**Comment by tallesaragao** [comment]
The device used to record the screen was a Xiaomi Mi 8 Lite (Android 10), but I had the same issue with other devices as well: Lenovo Vibe K6 (Android 7), Moto G5 (Android 8.1), ASUS Zenfone Max Pro M1 (Android 9) and Xiaomi Redmi Note 7 (Android 10).
