### ISSUE TITLE
[TimePicker] - Background colour is wrong with Material 18.1.4

### ISSUE THREAD

**Issue by hrandika** [ng-matero/extensions#331]
With the given theming instruction to M3 themes with above version shows a wrong background colour. 
![image](https://github.com/user-attachments/assets/57121b65-6a13-4275-9026-bc11ae10014f)

**Comment by nzbin** [comment]
I'm sorry, I can't reproduce with 18.1.4.
https://ng-matero.github.io/ng-matero/forms/datetime
