### ISSUE TITLE
how to use my component in formatter in MtxGrid

### ISSUE THREAD

**Issue by mr-karimiii** [ng-matero/extensions#34]
I want to use my custom component in MtxGrid like that:

```
formatter: (data) => `<custom-component [date]="${data.value}"></custom-component>`
```

and it's didn't work...

**Comment by mr-karimiii** [comment]
I think you must use DomSanitizer for bypass 'formatter' value...

**Comment by nzbin** [comment]
If you use your custom component, you should use custom cell template ([Demo](https://ng-matero.github.io/extensions/components/data-grid/overview#custom-cell-template-2))

**Comment by mr-karimiii** [comment]
by that way i must repeat the code and this not optimized.

**Comment by vladimirdrayling** [comment]
Is there a possibility to use a custom component like this?

```ts
{ formatter: CustomComponent }
```
