### ISSUE TITLE
DatePicker min date not working correctly

### ISSUE THREAD

**Issue by gunwixor** [ng-matero/extensions#349]
That's wired. When **start datetime** choosed, it's minimum date of **end datetime**, but when I selected end date, it's still in current my pc time. Minimum date doesn't work correctly. I attached my record video.

https://github.com/user-attachments/assets/b530a7ee-052d-4a47-8ee6-ce0b4abdccce

**Comment by nzbin** [comment]
@JelleBruisten Do you know this issue?

**Comment by JelleBruisten** [comment]
@nzbin I don't seem to experience this bug, and we use multiple min/max dates through the system.

**Comment by gunwixor** [comment]
@JelleBruisten  I'm using MomentDateAdapter.

**Comment by nzbin** [comment]
Can you provide an online example?

**Comment by nzbin** [comment]
Duplicate of #344

**Comment by gunwixor** [comment]
@nzbin  It's not completed yet.

**Comment by JelleBruisten** [comment]
It's a duplicate issue it seems
