### ISSUE TITLE
Action buttons: When selecting only the hour while using action buttons, time does not get saved.

### ISSUE THREAD

**Issue by davisriska** [ng-matero/extensions#357]
Reproduction: https://ng-matero.github.io/extensions/components/datetimepicker/overview

1. Check action buttons option
2. Select the date and the hour but don't select the minutes
3. Press apply.

The date will be changed, but the hour of time wont be changed.

**Comment by nzbin** [comment]
@CnxAtanasIliev Can you help me to fix it?

**Comment by nzbin** [comment]
18.2.4 has fixed.
