### ISSUE TITLE
[Grid] Grid Customized Question

### ISSUE THREAD

**Issue by leow1986** [ng-matero/extensions#360]
Hi There,

I have a case with much fields without pagination, so the x-axis scrollbar displayed on the bottom of the data grid. However, It's a little inconvenience for user to scroll down then scroll right. It's possible to setup an other scrollbar on the top of the grid?

Another case is a grid with pagination but with a large pagesize, so I'd like to ask is there any way to add another paginator on the toolbar?  I think it might be integrated the material paginator and hook all the event to the grid? or it is possible to inject/override the grid.html, will it be easier?

I appreciate you contribute such convenience framework. The data grid is very helpful to me to handle many kinds of data.

**Comment by nzbin** [comment]
> I have a case with much fields without pagination, so the x-axis scrollbar displayed on the bottom of the data grid. However, It's a little inconvenience for user to scroll down then scroll right. It's possible to setup an other scrollbar on the top of the grid?

<kbd>Shift</kbd> + scroll

> Another case is a grid with pagination but with a large pagesize, so I'd like to ask is there any way to add another paginator on the toolbar? I think it might be integrated the material paginator and hook all the event to the grid? or it is possible to inject/override the grid.html, will it be easier?

```scss
.mtx-grid {
  height: 100vh;
}
```
