### ISSUE TITLE
[DateTimePicker] When using action buttons, in some cases, apply is not working properly

### ISSUE THREAD

**Issue by ragnar-pals** [ng-matero/extensions#361]
Version: 18.2.4

When we have a datetimepicker with 'date' as type and we have action buttons, applying a date wont work as it should.

```HTML
...
  <mtx-datetimepicker
        #datetimePicker
        color="primary"
        type="date"
    >
        <mtx-datetimepicker-actions>
            <div class="flex justify-between w-full">
                <button
                    mat-button
                    (click)="setToday()"
                >Today</button>

                <button
                    mat-button
                    mtxDatetimepickerApply
                >Apply</button>
            </div>
        </mtx-datetimepicker-actions>
    </mtx-datetimepicker>
...
```

To replicate:  

1. Add actions buttons to DateTimePicker
2. Click calendar icon to open the calendar
3. Pick a date
4. Click outside the dialog to close it
5. Click calendar icon again
6. Click on the same date
7. Click apply button
8. Input will not update

I know that if you do not do the step nr. 6, clicking the Apply button will work. 
But some users might not do think of doing that and that might cause a misunderstanding.

The check for date difference is in _selectManually function in datetimepicker.ts on line 422.  
`... (!this._dateAdapter.sameDatetime(this.oldValue, this._selected)`

And when we select a date the _select function will set the oldValue and _selected value which will be the same when user opens the dialog up again in this case.

``` Typescript
/** Selects the given date */
  _select(date: D): void {
    this.oldValue = this._selected;
    this._selected = date;
    if (!this._actionsPortal) {
      if (!this._dateAdapter.sameDatetime(this.oldValue, this._selected)) {
        this.selectedChanged.emit(date);
      }
    }
  }

  _selectManually(): void {
    if (!this._selected) {
      this._selected = this._dateAdapter.today();
      this.selectedChanged.emit(this._selected);
    } else if (!this._dateAdapter.sameDatetime(this.oldValue, this._selected)) {
      this.selectedChanged.emit((this._selected as D) || (this.oldValue as D));
    }
    this.close();
  }
```

What I think would be expected is that a user can click on the previously selected date and hit apply and it should have that value.

**Comment by nzbin** [comment]
@CnxAtanasIliev Can you help me to fix the issue?

**Comment by nzbin** [comment]
18.3.1 has fixed.

**Comment by ragnar-pals** [comment]
Perfect!
That was quick. Thank you all :smiley:
