### ISSUE TITLE
[mtx-select] No custom labelling capability outside of `bindLabel`

### ISSUE THREAD

**Issue by WildeTechSolutions** [ng-matero/extensions#372]
While `bindLabel` is a convenient property to set, it does not allow for custom labels such as 

`${person.firstName} ${person.lastName}`

as an example.  It would be great if we could pass a `displayWith` function.  

Also, on a similar note, it would be nice to be able to customize the display of the dropdown versus the selected option.  i.e.

```html
<mat-select-trigger>
       {{ formatter.formatSelectedChoice(matSelect.value)}}
</mat-select-trigger>
<mat-option *ngFor="let values of service.allItems$ | async" [value]="person">
       {{ formatter.formatDropDownChoice(person)}}
</mat-option>
```

In this example, we could be formatting the selected person with just firstName and lastName, while we may opt to format the dropdown choices with a trailing employee id.  

This component library is very impressive! Thank you for your hard work!!

**Comment by nzbin** [comment]
The mtx-select is only a wrapper of ng-select, do you check the ng-select examples?
https://github.com/ng-select/ng-select
