### ISSUE TITLE
[DateTimePicker] Not updating hour automatically when no apply button is present

### ISSUE THREAD

**Issue by Meisbigmad** [ng-matero/extensions#373]
When using the datetimepicker without timeInput the hour is not automatically updated in the form value, even though no apply or cancel button is present in the 'clock' picker, the user is required to pick the minutes for the hour to be updated.

So when the user is just changing the hour and clicking away to close the datetimepicker, the hour is not updated causing confusion for the user.

``` 
<mat-form-field>
      <mat-label>Date</mat-label>
      <input matInput [mtxDatetimepicker]="picker" formControlName="date">
      <mtx-datetimepicker-toggle matSuffix [for]="picker"></mtx-datetimepicker-toggle>
      <mtx-datetimepicker #picker></mtx-datetimepicker>
</mat-form-field>
```

Following Image directly taken from de dev-app from this repo.
![image](https://github.com/user-attachments/assets/894ad455-4cc2-4718-8216-f2d904d38d7d)

**Comment by nzbin** [comment]
18.3.4 has fixed.
