### ISSUE TITLE
Angular 19 compatibility

### ISSUE THREAD

**Issue by ale-caramia** [ng-matero/extensions#378]
Could you provide an estimated timeline for when we can expect an update supporting Angular 19?
Thanks in advance

**Comment by nzbin** [comment]
I'm very busy now and I haven't enough time to do open source project. Maybe I will update v19 next month.

**Comment by mindarchitect** [comment]
> I'm very busy now and I haven't enough time to do open source project. Maybe I will update v19 next month.

Could you please update for 19 as soon as possible? Thank You very much! Best regards

**Comment by nzbin** [comment]
> > I'm very busy now and I haven't enough time to do open source project. Maybe I will update v19 next month.
> 
> Could you please update for 19 as soon as possible? Thank You very much! Best regards

Maybe next week.

**Comment by nzbin** [comment]
v19 has released.
