### ISSUE TITLE
Issue with disable check in mtx-grid

### ISSUE THREAD

**Issue by Huuvinh94** [ng-matero/extensions#38]
Hi @nzbin 
In `mtx-grid`, i set properties `rowSelectable` , then there are 2 cases that happened:

**Case 1:**
  When disabled checked row, same as the picture below:
![image](https://user-images.githubusercontent.com/18391623/95952087-adf29d00-0e21-11eb-975d-19b882493573.png)
  => I change `checked all`, at row checked disabled can still be change it was disabled:
![image](https://user-images.githubusercontent.com/18391623/95952110-b6e36e80-0e21-11eb-875e-d8495b99ec48.png)

**Case 2:**
How to disable checked all when all checked in row was disabled?

**Comment by nzbin** [comment]
Thanks for your advice, this issue has been fixed.
