### ISSUE TITLE
[DateTimePicker]: Current or Selected Day Highlighted in Other Months  

### ISSUE THREAD

**Issue by bah99** [ng-matero/extensions#380]
Hello,  

I'm not sure if this is a feature or an unintended behavior, but the current day or the selected day is being highlighted for all months, regardless of whether the date is relevant. This behavior is confusing and inconsistent with how Angular Material date pickers function.  

#### Examples  

- **Current Day (Not Selected)**:  
  In the following screenshots, the current day's date is highlighted in every month, even when navigating to months where it doesn't make sense.  

  ![Current Day Highlight 1](https://github.com/user-attachments/assets/391bde37-5a4c-40d2-8bcd-bad15cc586da)  
  ![Current Day Highlight 2](https://github.com/user-attachments/assets/ee11cfab-c239-4efe-8238-70e1c4a2f7da)  

- **Selected Day**:  
  Similarly, when a specific day is selected, it appears highlighted across all months, creating further confusion:  

  ![Selected Day Highlight 1](https://github.com/user-attachments/assets/cd8370e5-0923-4a51-8e0c-00cfb7b5839c)  
  ![Selected Day Highlight 2](https://github.com/user-attachments/assets/02174e15-3c15-4f41-9e67-0e6553373f0b)  

#### Question  

Is this an expected feature, or does it require a fix? If it's intentional, is there a way to disable this behavior? It seems inconsistent with the standard Angular Material date picker implementation.  

Thank you in advance for your help!

**Comment by bah99** [comment]
#381

**Comment by nzbin** [comment]
Thanks for your PR, the active cell logic is correct but it should be enhanced. The gray cell should only be highlighted when keyboard focused. Please check the Material does.

![image](https://github.com/user-attachments/assets/007c6244-15cd-42b4-bc56-e44f8f667f3a)

The datetimepicker's a11y is not very well now.

**Comment by nzbin** [comment]
v19 has released and try again.

**Comment by bah99** [comment]
It's fixed now, thank you!

However, for the 'Datetimepicker Inline,' the selected date is no longer highlighted or colored. Could you please check this?

**Comment by nzbin** [comment]
> It's fixed now, thank you!
> 
> However, for the 'Datetimepicker Inline,' the selected date is no longer highlighted or colored. Could you please check this?

Do you use the two-way binding?

```html
<mtx-calendar [(selected)]="selectedDate" />
```

**Comment by bah99** [comment]
> > It's fixed now, thank you!
> 
> > 
> 
> > However, for the 'Datetimepicker Inline,' the selected date is no longer highlighted or colored. Could you please check this?
> 
> 
> 
> Do you use the two-way binding?
> 
> 
> 
> ```html
> 
> <mtx-calendar [(selected)]="selectedDate" />
> 
> ```

No I'm not using it, I've just tested it from the [demo](https://ng-matero.github.io/extensions/components/datetimepicker/overview).
