### ISSUE TITLE
Angular 19 compilation error (Select control)

### ISSUE THREAD

**Issue by mindarchitect** [ng-matero/extensions#382]
Compilation error after updating to Angular 19:

Error: node_modules/@ng-matero/extensions/select/select.d.ts:44:5 - error TS2416: Property 'ngControl' in type 'MtxSelect' is not assignable to the same property in base type 'MatFormFieldControl<any>'.
  Type 'NgControl' is not assignable to type 'AbstractControlDirective | NgControl | null'.
    Type 'import(".../node_modules/@ng-matero/extensions/node_modules/@angular/forms/index").NgControl' is not assignable to type 'import(".../node_modules/@angular/forms/index").NgControl'.
      Types of property 'control' are incompatible.
        Type 'import(".../node_modules/@ng-matero/extensions/node_modules/@angular/forms/index").AbstractControl<any, any> | null' is not assignable to type 'import(".../node_modules/@angular/forms/index").AbstractControl<any, any> | null'.
          Type 'import(".../node_modules/@ng-matero/extensions/node_modules/@angular/forms/index").AbstractControl<any, any>' is not assignable to type 'import(".../node_modules/@angular/forms/index").AbstractControl<any, any>'.
            Types have separate declarations of a private property '_parent'.

44     ngControl: NgControl;

"@angular-devkit/build-angular": "~19.0.5",
"@angular/cli": "~19.0.5",
"@angular/compiler-cli": "~19.0.4",
"@ng-matero/extensions": "^18.4.0",

**Comment by nzbin** [comment]
v19 has released and try again.
