### ISSUE TITLE
[Grid] Column resize event

### ISSUE THREAD

**Issue by Rado-1** [ng-matero/extensions#386]
Is there any way how to detect that a resizable column has been resized? If not, I would appreciate an output of the MtxGrid for that. For example:

```
export interface MtxColumnResize {
    /** The id of the column being resized. */
    active: string;
    /** The column width. */
    width: number;
}

@Output() columnWidthChange = new EventEmitter<MtxColumnResize>();
```
or simply reuse `MtxGridColumn` with updated `width `property:
```
@Output() columnWidthChange = new EventEmitter<MtxGridColumn>(); 
```
This feature is needed to detect and save configuration of grid columns in an application and restore them when application/grid is reopened again.

**Comment by nzbin** [comment]
The v19 has exposed the ColumnResize instance

```ts
@ViewChild('grid', { static: true }) grid!: MtxGrid;

this.grid.columnResize?.columnResizeNotifier.resizeCompleted.subscribe(v => {
  console.log(v);
});
```

**Comment by Rado-1** [comment]
Thanks! I appreciate your speed :) However, to be "compatible" with other events produced by MtxGrid, you should think about regular documented @Output in future.
