### ISSUE TITLE
10.6.0 mtx-grid pinned无法锁住表头

### ISSUE THREAD

**Issue by BrutHellman** [ng-matero/extensions#40]
10.6.0 mtx-grid pinned无法锁住表头

**Comment by BrutHellman** [comment]
对比查了一下问题，是有个样式影响了

.theme-dark .mat-header-cell {
  position: relative;
}

现在暂时的解决方法是在当前模块的css中加上
.theme-dark .mat-header-cell {
  position: sticky !important;
}

**Comment by nzbin** [comment]
这个问题是 column resize 模块引起的，应该算是 material 官方的一个 bug，可以手动修复一下。我会在后面的版本修复。
