### ISSUE TITLE
ng-select label does not float if value is 0

### ISSUE THREAD

**Issue by davidhel** [ng-matero/extensions#42]
Repro steps:
In the list of items for combobox, let one element have value 0. Then select that element and click outside combobox to make it loose focus.

If value === 1:
![image](https://user-images.githubusercontent.com/6419075/98682206-ef646280-2363-11eb-926b-6a6ab3197a71.png)

if value === 0:
![image](https://user-images.githubusercontent.com/6419075/98682101-d065d080-2363-11eb-8c1a-300a65789654.png)

**Comment by nzbin** [comment]
`v10.8.0` has fixed.
