### ISSUE TITLE
Choose focus button in Dialog

### ISSUE THREAD

**Issue by keesjankoster** [ng-matero/extensions#44]
Hi!

Is it possible to implement a way to choose the button that is focussed/active on the dialog?

Something like:

```
buttons: [
  {
    type: '',
    text: 'Cancel',
    onClick: () => {cancel()}
  },
  {
    type: 'primary',
    text: 'Delete',
    focus: true,
    onClick: () => {delete()},
  },
]
```

Currently the first button is always focussed/active, it would be great if there was a way to choose.

Kees-Jan

**Comment by nzbin** [comment]
`v10.13.0` has supported it. Please check the latest [example](https://ng-matero.github.io/extensions/components/dialog/overview#basic-confirmation)

```diff
buttons: [
  {
    type: 'primary',
    text: 'Delete',
+   focusInitial: true,
    onClick: () => delete(),
  },
]
```
