### ISSUE TITLE
add a null value into mtx-select

### ISSUE THREAD

**Issue by khanhsnd** [ng-matero/extensions#45]
I'm added item into [items] with null value, then select it and click outside it became:
 
![image](https://user-images.githubusercontent.com/26472979/100302804-b1a34300-2fcd-11eb-92b1-58b1d86c5be8.png)
with mat-select, when select null value, it will back to normal
sorry for my bad English
please help me !

**Comment by nzbin** [comment]
You can try the latest version.

**Comment by khanhsnd** [comment]
I'm really try this. But i'm using **appearance="outline"** with mat-form-field and it 's not work :(
I'm lose my label when I choosing a value.

**Comment by nzbin** [comment]
If you use the version v12 or above, you can use the following css to fix.

```css
.mtx-select-empty .ng-value {
  display: none;
}
```
