### ISSUE TITLE
Angular Language Service conflicts with MtxGridComponent 'data' field having the type never[]

### ISSUE THREAD

**Issue by FinalButterfly** [ng-matero/extensions#55]
Hello.

Enabling strictTemplates in angularCompilerOptions while using Angular Language Service prevents my application from compiling, since the 'data' field in MtxGridComponent has the type 'never[]', instead of 'any[]' . 'never[]' and 'any[]' don't have any cross-over, therefore it's not possible to pass anything to MtxGrid without causing compilation errors.

![image](https://user-images.githubusercontent.com/31434462/118962713-1937bb00-b97f-11eb-8b2c-8a0e061e53bb.png)

![image](https://user-images.githubusercontent.com/31434462/118962880-4be1b380-b97f-11eb-9c55-668b3b83d118.png)

**Comment by nzbin** [comment]
I have fixed this issue, try the new version `v11.3.3`

**Comment by FinalButterfly** [comment]
The latest version fixes the issue, thanks a lot.
