### ISSUE TITLE
关于 Data Grid 的 multiple 模式

### ISSUE THREAD

**Issue by yujian340** [ng-matero/extensions#62]
“you can press ctrl/command + click or select checkboxs to choose multiple row.”

请问，是否存在一个属性，可以让我直接点击行来实现多选，目前的情况是，点击行会清除掉已选择的所有行，并单独选中点击行，这似乎不符合一般用户的操作习惯，是我的配置有错误么？

[rowSelectable]="true"
[rowSelected]="rowSelected"
[multiSelectable]="true"
[cellSelectable] = "false"

劳烦您给予解答，谢谢

**Comment by nzbin** [comment]
目前多选只能配合键盘使用, 下个版本优化一下

**Comment by nzbin** [comment]
`v12.1.0` has improved.
