### ISSUE TITLE
mtx-color-picker- Feature Request - access underlying input element

### ISSUE THREAD

**Issue by Abdullah0991** [ng-matero/extensions#64]
Hello,

It would by amazing if the `mtx-color-picker` component had a method to allow access the underlying `input` element for some really helpful purposes like: validation - readonly- etc...

**Comment by nzbin** [comment]
Have you tried `disabled` property?

**Comment by Abdullah0991** [comment]
Actually, I didn't :)
I thought it would disable the whole control.

It is kind helpful in my situation but I think it will be more helpful if I can set the input to `readonly`, the `disabled` state of the control could be confusing from the user perspective.

**Comment by nzbin** [comment]
Maybe I lost the `readonly` property, I will fix it as soon as possible. In addition, I want to refactor color picker making it more flexible.

**Comment by nzbin** [comment]
`v12.1.1` has fixed.
