### ISSUE TITLE
Checkbox touch event missing

### ISSUE THREAD

**Issue by pedroestabruxelles** [ng-matero/extensions#70]
When selecting a checkbox,  it's not being marked as touched.
In my specific scenario I am integrating with a mat-form-field (custom directive) and the error class is not being added due to touched being always false.

**Comment by nzbin** [comment]
Can you give me an example on [stackblitz](https://stackblitz.com/)?

**Comment by pedroestabruxelles** [comment]
Sure but I haven't been able to add the lib there. 
Im getting errors on both 11 and 12. 
"ngcc failed to run on @ng-matero/extensions@11.4.1."
On version 12 complains about ngx-colors not being able to compile...
Also tried what you suggested here https://github.com/ng-matero/extensions/issues/68 but no success..

Can you provide a working stackblitz with the lib?

**Comment by nzbin** [comment]
There has some problems with stackblitz. I think you can create a GitHub repo and let me test.

**Comment by pedroestabruxelles** [comment]
https://github.com/pedroestabruxelles/checkboxes-touched

**Comment by nzbin** [comment]
Many thanks, I got it.

**Comment by nzbin** [comment]
`v12.2.4` has fixed it.
