### ISSUE TITLE
dataGrid: how to set paginator to first page

### ISSUE THREAD

**Issue by mafeifan** [ng-matero/extensions#72]
there is  a reset button on my page with dataGrid component, when I click reset button, I want to set paginator to the first page, I tried set pageIndex  = 1, but it doesn't work

**Comment by nzbin** [comment]
I have updated the [remote data demo](https://ng-matero.github.io/extensions/components/grid/overview#remote-data) of data grid, you can try with clicking the reset button.

https://github.com/ng-matero/extensions/blob/45ac3e4d550b71ac81e37c7423c75564b7a3c6d7/projects/docs/src/app/pages/components/grid/examples/remote-data/app.component.ts#L90-L94
