### ISSUE TITLE
Sidesheet/Rightsheet Component

### ISSUE THREAD

**Issue by DaSchTour** [ng-matero/extensions#77]
Because of this https://github.com/angular/components/issues/13070 open issue at angular material I created my [own project with material extensions](https://github.com/footageone/angular-material-addons). But maybe this project would be a good home.

I would create a PR for this if it fits here.

**Comment by nzbin** [comment]
In fact, I have created a drawer component that can be opened from `top`, `bottom`, `right`, `left`. Maybe I will publish it in `13.1.0`.

**Comment by nzbin** [comment]
`v13.1.0` has addded the `drawer` component, please check the [docs](https://ng-matero.github.io/extensions/components/drawer/overview).
