### ISSUE TITLE
Data Grid internal link without reloading the page.

### ISSUE THREAD

**Issue by AlbertoGODev** [ng-matero/extensions#78]
Hi, 
I want an element in the row to be a link to an internal path without reloading the page. I have tried with formatter but the routerLink does not work. 

```
    {
      header: 'Site name',
      field: 'name',
      formatter: (data: any) => `<a href='/sites/${data.id}' routerLink='/sites,${data.id}' >${data.name}</a>`
    }
```

Is there a way to do it or can it be a future improvement?
Thanks.

**Comment by nzbin** [comment]
You should use custom cell template.

https://ng-matero.github.io/extensions/components/grid/overview#custom-cell-template-2

**Comment by AlbertoGODev** [comment]
Quite right! Thanks.
