### ISSUE TITLE
Data Grid Case insensitive Sorting

### ISSUE THREAD

**Issue by skuchhadiya** [ng-matero/extensions#79]
Current Behavior:  Currently only work with Case sensitive Sorting;
Expected Behavior :  Should be able to provide configuration for Case sensitive Sorting or Case insensitive Sorting either at grid level or column level.

![sorting bug](https://user-images.githubusercontent.com/46798192/146393651-5d96c2f6-730c-4ba8-95a6-aa181790d920.PNG)

**Comment by nzbin** [comment]
The sorting on frontend is powered by `mat-sort-header`. I haven't found config for case sensitive.

**Comment by skuchhadiya** [comment]
> The sorting on frontend is powered by `mat-sort-header`. I haven't found config for case sensitive.

Yes,  I know that, At the moment there is no config facility, I wish if we have that function. At the moment mat-sort-header is behaving differently than the mat-table and mtx-grid. At the moment there is no way we can make column sorting by  Case insensitive
