### ISSUE TITLE
MTX_DATETIME_FORMATS not working 

### ISSUE THREAD

**Issue by roddc** [ng-matero/extensions#80]
I want to customize the datetime input display, but it is not working, I copy the example from the docs.
```
 providers: [
        {
            provide: MTX_DATETIME_FORMATS,
            useValue: {
                parse: {
                    dateInput: 'YYYY-MM-DD',
                    monthInput: 'MMMM',
                    timeInput: 'HH:mm',
                    datetimeInput: 'YYYY-MM-DD HH:mm',
                },
                display: {
                    dateInput: 'YYYY-MM-DD',
                    monthInput: 'MMMM',
                    timeInput: 'HH:mm',
                    datetimeInput: 'yyyy/MM/dd HH:mm:ss',
                    monthYearLabel: 'YYYY MMMM',
                    dateA11yLabel: 'LL',
                    monthYearA11yLabel: 'MMMM YYYY',
                    popupHeaderDateLabel: 'MMM DD, ddd',
                },
            },
        },
    ],
```
![image](https://user-images.githubusercontent.com/9416290/147474290-1062454d-5c1c-466d-944c-5f6c42ca9ed5.png)

**Comment by nzbin** [comment]
Is there some errors in Console? You can check the demos [here](https://github.com/ng-matero/extensions/tree/master/projects/dev-app/src/app/datetimepicker).

**Comment by roddc** [comment]
It will throw error if I don't import `MtxNativeDatetimeModule`, I imported the module, but the format is still the same, I am not sure it is because I imported `MatDatepickerModule` as well

**Comment by nzbin** [comment]
I created a [online example](https://stackblitz.com/edit/angular-be83mm?file=src%2Fapp%2Fmaterial-extensions-module.ts).

**Comment by wupaz** [comment]
Seem work on Angular v12 but didn't work on v13
https://angular-be83mm-5yyams.stackblitz.io

**Comment by nzbin** [comment]
> Seem work on Angular v12 but didn't work on v13 https://angular-be83mm-5yyams.stackblitz.io

The [demo](https://ng-matero.github.io/extensions/components/datetimepicker/overview) is v13. I'm not sure where has the problems, maybe you should provide some testing codes.

**Comment by llyrowenjones** [comment]
> I had the same error and after quite a bit of research it turns out that by adding `{ provide: DateAdapter, useClass: MomentDateAdapter }` it works as expected.

I had to also install `@angular/material-moment-adapter` and `@ng-matero/extensions-moment-adapter` to use the adapter.

I followed @nzbin's [above link](https://stackblitz.com/edit/angular-be83mm?file=src%2Fapp%2Fmaterial-extensions-module.ts) after installing these to make it work as I wanted.

**Comment by zzpzaf** [comment]
OK perhaps the solution is outdated now. But, from what I can understand, the solution works only with Moment.js-based adapter, i.e.:  @angular/material-moment-adapter and @ng-matero/extensions-moment-adapter ( MtxMomentDatetimeModule), and it fails with the native MtxNativeDatetimeModule.
