### ISSUE TITLE
Disable icon in grid

### ISSUE THREAD

**Issue by furzibada** [ng-matero/extensions#82]
I have been using the following code and I would like to disable the delete button based on the other column values.
Is there any way to individually disable delete button in a row based on the row column. I can either disable all or enable all. I do not see any control over row column.

Here is the snippet of my typescript:

```
columns: MtxGridColumn[] = [  
....
.....
 disabled: false,
          type: 'icon',
          text: 'delete',
          icon: 'delete',
          tooltip: 'Delete',
          color: 'warn',
          pop: true,
          popTitle: 'Confirm delete?',
          click: row => {
            this.deleteitem(row.itemid);
          },
```

**Comment by nzbin** [comment]
Maybe you can use the [custom cell](https://ng-matero.github.io/extensions/components/grid/overview#custom-cell-template-2)

**Comment by nzbin** [comment]
The new version 14.1.0 has improved.
