### ISSUE TITLE
mtx-select won't open on first click after formControl being enabled. 

### ISSUE THREAD

**Issue by JeanMeche** [ng-matero/extensions#89]
Suppose this component : 

```
@Component({
  selector: 'my-app',
  template: `
      <mtx-select
        [items]="['item1', 'item2', 'item3']"
        placeholder="Select"
        [formControl]="formControl"
      ></mtx-select>
`
,
})
export class AppComponent {
  isEnabled = false;

  formControl = new FormControl();

  constructor() {
    this.formControl.disable();
  }

  toggle() {
    this.isEnabled = !this.isEnabled;
    if (this.isEnabled) {
      this.formControl.enable();
    } else {
      this.formControl.disable();
    }
  }
}

```
After the first toggle disabled => enabled, the `mtx-select` component will open the suggestion list only after the 2nd click. 
This is probably because the inner ng-select is still considered as disabled. 
Note that this problem occurs only after the first toggle but after after the subsequent ones. 

As the following example will prove, this does not happend will a sole `ng-select`, so their is a faulty behaviour on the `mtx-select`

[Stackblitz demo](https://stackblitz.com/edit/angular-jzhrze?file=src%2Fapp%2Fapp.component.html)

**Comment by nzbin** [comment]
`v13.0.2` has released.
