### ISSUE TITLE
DateTimeAdapter for date-fns

### ISSUE THREAD

**Issue by inpercima** [ng-matero/extensions#93]
Hi, is there a DateFnsDateTimeAdapter for the DatePicker-Comoponent or has some any idea to plan this?

For an other older ilbrary someone created a Adapter for DateFns: https://gist.github.com/rovercoder/d223ff977194bc8ca389d853ad1ac81c#file-date-fns-date-time-adapter-class-ts

Is this possible for this component?

**Comment by nzbin** [comment]
```
npm i @ng-matero/extensions-date-fns-adapter
```
