### ISSUE TITLE
Documentation throws 404 after reload, but still works

### ISSUE THREAD

**Issue by dkimmich-onventis** [ng-matero/extensions#94]
I'm using a browser which detects 404 errors and offers me special features for this case. When using the documentation and navigating to another page than the home page, I noticed that after reloading the page, the web server returns a 404 error when loading the index.html. Despite throwing an error, the web server still delivers the HTML document correctly, so the page loads and works properly. Some browsers just might have implemented some logic for 404 case which will falsely be activated.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/68286501/158336911-ea766399-6e83-4834-acaf-8906a16dc48b.png">

**Comment by nzbin** [comment]
Because the docs use a history route and 404.html has the same content with index.html.
