### ISSUE TITLE
feature(drawer): add min and max width

### ISSUE THREAD

**Issue by mrmokwa** [ng-matero/extensions#95]
I'd be nice to be able to set the maximun width of the drawer.
I sugest using the same idea of @angular/components dialog, where you can set the dialog width and max width.

[maxWidth @angular/components/dialog](https://github.com/angular/components/blob/8ef3125285b3e5a4eb0b0f2974acaf3873e5eead/src/material/dialog/dialog-config.ts#L77)

```js
const config: MtxDrawerConfig = {
  width: '100vw',
  maxWidth: '1024px'
};
```

**Comment by mrmokwa** [comment]
For anyone else having his problem, you can do the following below to achieve this behavior:

1) Create css global rule

```
.max-width-400px {
   .mtx-drawer-content-wrapper {
      max-width: 400px;
   }
}
```
2) And use the panelClass from MtxDrawerConfig

`.open(Component, {data, panelClass: ['max-width-400px']}`

**Comment by nzbin** [comment]
The new version 14.2.0 has added this feature.
