### ISSUE TITLE
DateTimePicker format UTC

### ISSUE THREAD

**Issue by palmtreefrb** [ng-matero/extensions#96]
I need to format the datetimepicker timezone to UTC. Normally with one way binding [ngModel] I would just use a pipe but I am using two way binding [(ngModel)] so I can't use pipe. Is there another way I can display the date format to UTC?

 ```html
<mat-form-field>
  <input matInput [mtxDatetimepicker]="datetimePickerStart" [(ngModel)]="element[col.name]  | date:'yyyy-MM-dd HH:mm' :'UTC'">
    <mtx-datetimepicker-toggle matSuffix [for]="datetimePickerStart"></mtx-datetimepicker-toggle>
    <mtx-datetimepicker #datetimePickerStart
                        [type]="type"
                        [mode]="mode"
                        [multiYearSelector]="multiYearSelector"
                        [startView]="startView"
                        [twelvehour]="twelvehour"
                        [timeInterval]="timeInterval"
                        [touchUi]="touchUi"></mtx-datetimepicker>
</mat-form-field>
```

**Comment by nzbin** [comment]
You can provide the `MAT_MOMENT_DATE_ADAPTER_OPTIONS` in your `material.module.ts` (checkout [ng-matero](ng-matero)), please have a try.

```ts
@NgModule({
  providers: [
    {provide: MAT_MOMENT_DATE_ADAPTER_OPTIONS, useValue: {useUtc: true}}
  ]
})
```

[ng-matero]: https://github.com/ng-matero/ng-matero/blob/599332d7b670d52e8ba53f8bbd134c28c8f05675/src/app/material.module.ts#L92-L128

**Comment by palmtreefrb** [comment]
So how would the above be implemented to show local time in mtx-grid? With no column type the below times are still showing gmt time.

![Screenshot from 2022-03-25 08-30-06](https://user-images.githubusercontent.com/7799495/160152898-482641e7-12ef-4002-9c7a-33948e79daad.png)

If I change the column type to date, it will not display anything...

    {
      header: 'Temp Target',
      field: 'temperatureTarget',
      minWidth: 100,
    },
    {
      header: 'Start Time',
      field: 'startTime',
      minWidth: 100,
      type: 'date'
    },
    {
      header: 'End Time',
      field: 'endTime',
      minWidth: 100,
      type: 'date'
    }
![Screenshot from 2022-03-25 08-31-11](https://user-images.githubusercontent.com/7799495/160153466-71304e2d-887e-4055-bc15-f860e7ed4bae.png)

**Comment by palmtreefrb** [comment]
I am confused as to what date adapter should be used. In **material.module.ts** there is **MAT_DATE_FORMATS** and in **material-extensions.module.ts** there is **MTX_DATETIME_FORMATS**
Adding to this confusion, what formatting is being used in mtx-grid?
      typeParameter: {
        format: 'yyyy-MM-dd h:m a',
      },
The above format in moment should produce a lowercase "am/pm" but the display is uppercase 2022-03-25 12:15 AM

**Comment by nzbin** [comment]
Yes, they are different. In `mtx-grid`, it's formatted with [Angular DatePipe](https://angular.cn/api/common/DatePipe).
