### ISSUE TITLE
Feature Request: Tooltip position for action button

### ISSUE THREAD

**Issue by maphe** [ng-matero/extensions#98]
Hi, is there any chance you could add an option to position the tooltip on a button?
```
    {
      header: 'Operation',
      field: 'operation',
      width: '160px',
      pinned: 'right',
      right: '0px',
      type: 'button',
      buttons: [
        {
          type: 'icon',
          text: 'copy',
          icon: 'file_copy',
          tooltip: 'copy',
          tooltipPosition: 'left', // <------ something like that
          disabled: true,
          click: () => {
            alert('copy');
          },
        },
      ],
    }
```

The issue with how it is right now, is that the toolbox appears below and often it covers the button on the next row, so when a user wants to hover the button below they end up hovering the tooltip.

Thanks

**Comment by nzbin** [comment]
Maybe it should be enhanced, but you can also use [custom template](https://ng-matero.github.io/extensions/components/grid/overview#custom-cell-template-2) to achieve it.

**Comment by maphe** [comment]
Yeah thanks I'll use the workaround for now.

**Comment by nzbin** [comment]
The new version 14.1.0 has improved.

**Comment by maphe** [comment]
Cool, thank you! Working perfectly 👍
